// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	ports "laguna-escondida/backend/pkg/domain/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockEventSubscriber is an autogenerated mock type for the EventSubscriber type
type MockEventSubscriber struct {
	mock.Mock
}

type MockEventSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriber) EXPECT() *MockEventSubscriber_Expecter {
	return &MockEventSubscriber_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockEventSubscriber) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventSubscriber_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventSubscriber_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventSubscriber_Expecter) Close() *MockEventSubscriber_Close_Call {
	return &MockEventSubscriber_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventSubscriber_Close_Call) Run(run func()) *MockEventSubscriber_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSubscriber_Close_Call) Return(_a0 error) *MockEventSubscriber_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventSubscriber_Close_Call) RunAndReturn(run func() error) *MockEventSubscriber_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockEventSubscriber) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventSubscriber_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockEventSubscriber_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventSubscriber_Expecter) Start(ctx interface{}) *MockEventSubscriber_Start_Call {
	return &MockEventSubscriber_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockEventSubscriber_Start_Call) Run(run func(ctx context.Context)) *MockEventSubscriber_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEventSubscriber_Start_Call) Return(_a0 error) *MockEventSubscriber_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventSubscriber_Start_Call) RunAndReturn(run func(context.Context) error) *MockEventSubscriber_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: handler
func (_m *MockEventSubscriber) Subscribe(handler ports.EventHandler) error {
	ret := _m.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ports.EventHandler) error); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - handler ports.EventHandler
func (_e *MockEventSubscriber_Expecter) Subscribe(handler interface{}) *MockEventSubscriber_Subscribe_Call {
	return &MockEventSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", handler)}
}

func (_c *MockEventSubscriber_Subscribe_Call) Run(run func(handler ports.EventHandler)) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ports.EventHandler))
	})
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) Return(_a0 error) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) RunAndReturn(run func(ports.EventHandler) error) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventSubscriber creates a new instance of MockEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriber {
	mock := &MockEventSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
