// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventHandler is an autogenerated mock type for the EventHandler type
type MockEventHandler struct {
	mock.Mock
}

type MockEventHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventHandler) EXPECT() *MockEventHandler_Expecter {
	return &MockEventHandler_Expecter{mock: &_m.Mock}
}

// EventName provides a mock function with no fields
func (_m *MockEventHandler) EventName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEventHandler_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockEventHandler_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockEventHandler_Expecter) EventName() *MockEventHandler_EventName_Call {
	return &MockEventHandler_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockEventHandler_EventName_Call) Run(run func()) *MockEventHandler_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventHandler_EventName_Call) Return(_a0 string) *MockEventHandler_EventName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventHandler_EventName_Call) RunAndReturn(run func() string) *MockEventHandler_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: ctx, payload
func (_m *MockEventHandler) Handle(ctx context.Context, payload []byte) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockEventHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockEventHandler_Expecter) Handle(ctx interface{}, payload interface{}) *MockEventHandler_Handle_Call {
	return &MockEventHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, payload)}
}

func (_c *MockEventHandler_Handle_Call) Run(run func(ctx context.Context, payload []byte)) *MockEventHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockEventHandler_Handle_Call) Return(_a0 error) *MockEventHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventHandler_Handle_Call) RunAndReturn(run func(context.Context, []byte) error) *MockEventHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventHandler creates a new instance of MockEventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventHandler {
	mock := &MockEventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
