// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	ports "laguna-escondida/backend/pkg/domain/ports"

	mock "github.com/stretchr/testify/mock"
)

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, event
func (_m *MockEventBus) Publish(ctx context.Context, event ports.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event ports.Event
func (_e *MockEventBus_Expecter) Publish(ctx interface{}, event interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(ctx context.Context, event ports.Event)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.Event))
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return(_a0 error) *MockEventBus_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(context.Context, ports.Event) error) *MockEventBus_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
