// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// EventName provides a mock function with no fields
func (_m *MockEvent) EventName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEvent_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockEvent_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockEvent_Expecter) EventName() *MockEvent_EventName_Call {
	return &MockEvent_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockEvent_EventName_Call) Run(run func()) *MockEvent_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_EventName_Call) Return(_a0 string) *MockEvent_EventName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvent_EventName_Call) RunAndReturn(run func() string) *MockEvent_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
