// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockExpenseCategoryRepository is an autogenerated mock type for the ExpenseCategoryRepository type
type MockExpenseCategoryRepository struct {
	mock.Mock
}

type MockExpenseCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseCategoryRepository) EXPECT() *MockExpenseCategoryRepository_Expecter {
	return &MockExpenseCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockExpenseCategoryRepository) Create(ctx context.Context, category *dto.ExpenseCategory) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ExpenseCategory) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *dto.ExpenseCategory
func (_e *MockExpenseCategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *MockExpenseCategoryRepository_Create_Call {
	return &MockExpenseCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockExpenseCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *dto.ExpenseCategory)) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.ExpenseCategory))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_Create_Call) Return(_a0 error) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *dto.ExpenseCategory) error) *MockExpenseCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockExpenseCategoryRepository) FindAll(ctx context.Context) ([]*dto.ExpenseCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.ExpenseCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.ExpenseCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseCategoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockExpenseCategoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpenseCategoryRepository_Expecter) FindAll(ctx interface{}) *MockExpenseCategoryRepository_FindAll_Call {
	return &MockExpenseCategoryRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) Return(_a0 []*dto.ExpenseCategory, _a1 error) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.ExpenseCategory, error)) *MockExpenseCategoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function with given fields: ctx
func (_m *MockExpenseCategoryRepository) FindAllActive(ctx context.Context) ([]*dto.ExpenseCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []*dto.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.ExpenseCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.ExpenseCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseCategoryRepository_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockExpenseCategoryRepository_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpenseCategoryRepository_Expecter) FindAllActive(ctx interface{}) *MockExpenseCategoryRepository_FindAllActive_Call {
	return &MockExpenseCategoryRepository_FindAllActive_Call{Call: _e.mock.On("FindAllActive", ctx)}
}

func (_c *MockExpenseCategoryRepository_FindAllActive_Call) Run(run func(ctx context.Context)) *MockExpenseCategoryRepository_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAllActive_Call) Return(_a0 []*dto.ExpenseCategory, _a1 error) *MockExpenseCategoryRepository_FindAllActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindAllActive_Call) RunAndReturn(run func(context.Context) ([]*dto.ExpenseCategory, error)) *MockExpenseCategoryRepository_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *MockExpenseCategoryRepository) FindByCode(ctx context.Context, code string) (*dto.ExpenseCategory, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *dto.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ExpenseCategory, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ExpenseCategory); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseCategoryRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockExpenseCategoryRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockExpenseCategoryRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockExpenseCategoryRepository_FindByCode_Call {
	return &MockExpenseCategoryRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockExpenseCategoryRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockExpenseCategoryRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByCode_Call) Return(_a0 *dto.ExpenseCategory, _a1 error) *MockExpenseCategoryRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (*dto.ExpenseCategory, error)) *MockExpenseCategoryRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockExpenseCategoryRepository) FindByID(ctx context.Context, id string) (*dto.ExpenseCategory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.ExpenseCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ExpenseCategory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ExpenseCategory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockExpenseCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExpenseCategoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockExpenseCategoryRepository_FindByID_Call {
	return &MockExpenseCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) Return(_a0 *dto.ExpenseCategory, _a1 error) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseCategoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.ExpenseCategory, error)) *MockExpenseCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, category
func (_m *MockExpenseCategoryRepository) Update(ctx context.Context, id string, category *dto.ExpenseCategory) error {
	ret := _m.Called(ctx, id, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ExpenseCategory) error); ok {
		r0 = rf(ctx, id, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - category *dto.ExpenseCategory
func (_e *MockExpenseCategoryRepository_Expecter) Update(ctx interface{}, id interface{}, category interface{}) *MockExpenseCategoryRepository_Update_Call {
	return &MockExpenseCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, category)}
}

func (_c *MockExpenseCategoryRepository_Update_Call) Run(run func(ctx context.Context, id string, category *dto.ExpenseCategory)) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.ExpenseCategory))
	})
	return _c
}

func (_c *MockExpenseCategoryRepository_Update_Call) Return(_a0 error) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, string, *dto.ExpenseCategory) error) *MockExpenseCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseCategoryRepository creates a new instance of MockExpenseCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseCategoryRepository {
	mock := &MockExpenseCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
