// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	product "laguna-escondida/backend/internal/domain/aggregate/product"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockProductRepository) Create(ctx context.Context, _a1 *product.Aggregate) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.Aggregate) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *product.Aggregate
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, _a1 *product.Aggregate)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*product.Aggregate))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(context.Context, *product.Aggregate) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePreparationResponsibility provides a mock function with given fields: ctx, productID, area, priority
func (_m *MockProductRepository) CreatePreparationResponsibility(ctx context.Context, productID string, area string, priority int) (*dto.ProductPreparationResponsibility, error) {
	ret := _m.Called(ctx, productID, area, priority)

	if len(ret) == 0 {
		panic("no return value specified for CreatePreparationResponsibility")
	}

	var r0 *dto.ProductPreparationResponsibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*dto.ProductPreparationResponsibility, error)); ok {
		return rf(ctx, productID, area, priority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *dto.ProductPreparationResponsibility); ok {
		r0 = rf(ctx, productID, area, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductPreparationResponsibility)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, productID, area, priority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_CreatePreparationResponsibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePreparationResponsibility'
type MockProductRepository_CreatePreparationResponsibility_Call struct {
	*mock.Call
}

// CreatePreparationResponsibility is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - area string
//   - priority int
func (_e *MockProductRepository_Expecter) CreatePreparationResponsibility(ctx interface{}, productID interface{}, area interface{}, priority interface{}) *MockProductRepository_CreatePreparationResponsibility_Call {
	return &MockProductRepository_CreatePreparationResponsibility_Call{Call: _e.mock.On("CreatePreparationResponsibility", ctx, productID, area, priority)}
}

func (_c *MockProductRepository_CreatePreparationResponsibility_Call) Run(run func(ctx context.Context, productID string, area string, priority int)) *MockProductRepository_CreatePreparationResponsibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_CreatePreparationResponsibility_Call) Return(_a0 *dto.ProductPreparationResponsibility, _a1 error) *MockProductRepository_CreatePreparationResponsibility_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_CreatePreparationResponsibility_Call) RunAndReturn(run func(context.Context, string, string, int) (*dto.ProductPreparationResponsibility, error)) *MockProductRepository_CreatePreparationResponsibility_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePreparationResponsibility provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) DeletePreparationResponsibility(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePreparationResponsibility")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_DeletePreparationResponsibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePreparationResponsibility'
type MockProductRepository_DeletePreparationResponsibility_Call struct {
	*mock.Call
}

// DeletePreparationResponsibility is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepository_Expecter) DeletePreparationResponsibility(ctx interface{}, id interface{}) *MockProductRepository_DeletePreparationResponsibility_Call {
	return &MockProductRepository_DeletePreparationResponsibility_Call{Call: _e.mock.On("DeletePreparationResponsibility", ctx, id)}
}

func (_c *MockProductRepository_DeletePreparationResponsibility_Call) Run(run func(ctx context.Context, id string)) *MockProductRepository_DeletePreparationResponsibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_DeletePreparationResponsibility_Call) Return(_a0 error) *MockProductRepository_DeletePreparationResponsibility_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_DeletePreparationResponsibility_Call) RunAndReturn(run func(context.Context, string) error) *MockProductRepository_DeletePreparationResponsibility_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *MockProductRepository) FindAll(ctx context.Context, filter dto.ListProductsRequest) ([]*dto.Product, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListProductsRequest) ([]*dto.Product, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListProductsRequest) []*dto.Product); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ListProductsRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProductRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.ListProductsRequest
func (_e *MockProductRepository_Expecter) FindAll(ctx interface{}, filter interface{}) *MockProductRepository_FindAll_Call {
	return &MockProductRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *MockProductRepository_FindAll_Call) Run(run func(ctx context.Context, filter dto.ListProductsRequest)) *MockProductRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ListProductsRequest))
	})
	return _c
}

func (_c *MockProductRepository_FindAll_Call) Return(_a0 []*dto.Product, _a1 error) *MockProductRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindAll_Call) RunAndReturn(run func(context.Context, dto.ListProductsRequest) ([]*dto.Product, error)) *MockProductRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllCategories provides a mock function with given fields: ctx
func (_m *MockProductRepository) FindAllCategories(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllCategories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllCategories'
type MockProductRepository_FindAllCategories_Call struct {
	*mock.Call
}

// FindAllCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProductRepository_Expecter) FindAllCategories(ctx interface{}) *MockProductRepository_FindAllCategories_Call {
	return &MockProductRepository_FindAllCategories_Call{Call: _e.mock.On("FindAllCategories", ctx)}
}

func (_c *MockProductRepository_FindAllCategories_Call) Run(run func(ctx context.Context)) *MockProductRepository_FindAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProductRepository_FindAllCategories_Call) Return(_a0 []string, _a1 error) *MockProductRepository_FindAllCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindAllCategories_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockProductRepository_FindAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) FindByID(ctx context.Context, id string) (*dto.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProductRepository_FindByID_Call {
	return &MockProductRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockProductRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_FindByID_Call) Return(_a0 *dto.Product, _a1 error) *MockProductRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.Product, error)) *MockProductRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockProductRepository) FindByIDs(ctx context.Context, ids []string) ([]*dto.Product, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*dto.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*dto.Product, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*dto.Product); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockProductRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockProductRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockProductRepository_FindByIDs_Call {
	return &MockProductRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockProductRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) Return(_a0 []*dto.Product, _a1 error) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*dto.Product, error)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockProductRepository) FindByName(ctx context.Context, name string) (*dto.Product, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *dto.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Product, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Product); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockProductRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockProductRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockProductRepository_FindByName_Call {
	return &MockProductRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockProductRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockProductRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_FindByName_Call) Return(_a0 *dto.Product, _a1 error) *MockProductRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*dto.Product, error)) *MockProductRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySKUs provides a mock function with given fields: ctx, skus
func (_m *MockProductRepository) FindBySKUs(ctx context.Context, skus []string) ([]*dto.Product, error) {
	ret := _m.Called(ctx, skus)

	if len(ret) == 0 {
		panic("no return value specified for FindBySKUs")
	}

	var r0 []*dto.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*dto.Product, error)); ok {
		return rf(ctx, skus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*dto.Product); ok {
		r0 = rf(ctx, skus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, skus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindBySKUs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySKUs'
type MockProductRepository_FindBySKUs_Call struct {
	*mock.Call
}

// FindBySKUs is a helper method to define mock.On call
//   - ctx context.Context
//   - skus []string
func (_e *MockProductRepository_Expecter) FindBySKUs(ctx interface{}, skus interface{}) *MockProductRepository_FindBySKUs_Call {
	return &MockProductRepository_FindBySKUs_Call{Call: _e.mock.On("FindBySKUs", ctx, skus)}
}

func (_c *MockProductRepository_FindBySKUs_Call) Run(run func(ctx context.Context, skus []string)) *MockProductRepository_FindBySKUs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockProductRepository_FindBySKUs_Call) Return(_a0 []*dto.Product, _a1 error) *MockProductRepository_FindBySKUs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindBySKUs_Call) RunAndReturn(run func(context.Context, []string) ([]*dto.Product, error)) *MockProductRepository_FindBySKUs_Call {
	_c.Call.Return(run)
	return _c
}

// FindPreparationResponsibilityByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) FindPreparationResponsibilityByID(ctx context.Context, id string) (*dto.ProductPreparationResponsibility, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPreparationResponsibilityByID")
	}

	var r0 *dto.ProductPreparationResponsibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ProductPreparationResponsibility, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ProductPreparationResponsibility); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductPreparationResponsibility)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindPreparationResponsibilityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPreparationResponsibilityByID'
type MockProductRepository_FindPreparationResponsibilityByID_Call struct {
	*mock.Call
}

// FindPreparationResponsibilityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepository_Expecter) FindPreparationResponsibilityByID(ctx interface{}, id interface{}) *MockProductRepository_FindPreparationResponsibilityByID_Call {
	return &MockProductRepository_FindPreparationResponsibilityByID_Call{Call: _e.mock.On("FindPreparationResponsibilityByID", ctx, id)}
}

func (_c *MockProductRepository_FindPreparationResponsibilityByID_Call) Run(run func(ctx context.Context, id string)) *MockProductRepository_FindPreparationResponsibilityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_FindPreparationResponsibilityByID_Call) Return(_a0 *dto.ProductPreparationResponsibility, _a1 error) *MockProductRepository_FindPreparationResponsibilityByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindPreparationResponsibilityByID_Call) RunAndReturn(run func(context.Context, string) (*dto.ProductPreparationResponsibility, error)) *MockProductRepository_FindPreparationResponsibilityByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *MockProductRepository) Update(ctx context.Context, id string, _a2 *product.Aggregate) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *product.Aggregate) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - _a2 *product.Aggregate
func (_e *MockProductRepository_Expecter) Update(ctx interface{}, id interface{}, _a2 interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, _a2)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, id string, _a2 *product.Aggregate)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*product.Aggregate))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(context.Context, string, *product.Aggregate) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreparationResponsibility provides a mock function with given fields: ctx, id, area, priority
func (_m *MockProductRepository) UpdatePreparationResponsibility(ctx context.Context, id string, area string, priority int) (*dto.ProductPreparationResponsibility, error) {
	ret := _m.Called(ctx, id, area, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreparationResponsibility")
	}

	var r0 *dto.ProductPreparationResponsibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*dto.ProductPreparationResponsibility, error)); ok {
		return rf(ctx, id, area, priority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *dto.ProductPreparationResponsibility); ok {
		r0 = rf(ctx, id, area, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductPreparationResponsibility)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, id, area, priority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_UpdatePreparationResponsibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreparationResponsibility'
type MockProductRepository_UpdatePreparationResponsibility_Call struct {
	*mock.Call
}

// UpdatePreparationResponsibility is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - area string
//   - priority int
func (_e *MockProductRepository_Expecter) UpdatePreparationResponsibility(ctx interface{}, id interface{}, area interface{}, priority interface{}) *MockProductRepository_UpdatePreparationResponsibility_Call {
	return &MockProductRepository_UpdatePreparationResponsibility_Call{Call: _e.mock.On("UpdatePreparationResponsibility", ctx, id, area, priority)}
}

func (_c *MockProductRepository_UpdatePreparationResponsibility_Call) Run(run func(ctx context.Context, id string, area string, priority int)) *MockProductRepository_UpdatePreparationResponsibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_UpdatePreparationResponsibility_Call) Return(_a0 *dto.ProductPreparationResponsibility, _a1 error) *MockProductRepository_UpdatePreparationResponsibility_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_UpdatePreparationResponsibility_Call) RunAndReturn(run func(context.Context, string, string, int) (*dto.ProductPreparationResponsibility, error)) *MockProductRepository_UpdatePreparationResponsibility_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
