// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	bill "laguna-escondida/backend/internal/domain/aggregate/bill"

	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockBillRepository is an autogenerated mock type for the BillRepository type
type MockBillRepository struct {
	mock.Mock
}

type MockBillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillRepository) EXPECT() *MockBillRepository_Expecter {
	return &MockBillRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1, products
func (_m *MockBillRepository) Create(ctx context.Context, _a1 *bill.Aggregate, products []*dto.Product) error {
	ret := _m.Called(ctx, _a1, products)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bill.Aggregate, []*dto.Product) error); ok {
		r0 = rf(ctx, _a1, products)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *bill.Aggregate
//   - products []*dto.Product
func (_e *MockBillRepository_Expecter) Create(ctx interface{}, _a1 interface{}, products interface{}) *MockBillRepository_Create_Call {
	return &MockBillRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1, products)}
}

func (_c *MockBillRepository_Create_Call) Run(run func(ctx context.Context, _a1 *bill.Aggregate, products []*dto.Product)) *MockBillRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bill.Aggregate), args[2].([]*dto.Product))
	})
	return _c
}

func (_c *MockBillRepository_Create_Call) Return(_a0 error) *MockBillRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillRepository_Create_Call) RunAndReturn(run func(context.Context, *bill.Aggregate, []*dto.Product) error) *MockBillRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockBillRepository) FindAllByCriteria(ctx context.Context, criteria *dto.BillCriteria) ([]dto.InvoiceListItem, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCriteria")
	}

	var r0 []dto.InvoiceListItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.BillCriteria) ([]dto.InvoiceListItem, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.BillCriteria) []dto.InvoiceListItem); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InvoiceListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.BillCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_FindAllByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByCriteria'
type MockBillRepository_FindAllByCriteria_Call struct {
	*mock.Call
}

// FindAllByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.BillCriteria
func (_e *MockBillRepository_Expecter) FindAllByCriteria(ctx interface{}, criteria interface{}) *MockBillRepository_FindAllByCriteria_Call {
	return &MockBillRepository_FindAllByCriteria_Call{Call: _e.mock.On("FindAllByCriteria", ctx, criteria)}
}

func (_c *MockBillRepository_FindAllByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.BillCriteria)) *MockBillRepository_FindAllByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.BillCriteria))
	})
	return _c
}

func (_c *MockBillRepository_FindAllByCriteria_Call) Return(_a0 []dto.InvoiceListItem, _a1 error) *MockBillRepository_FindAllByCriteria_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_FindAllByCriteria_Call) RunAndReturn(run func(context.Context, *dto.BillCriteria) ([]dto.InvoiceListItem, error)) *MockBillRepository_FindAllByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockBillRepository) FindByCriteria(ctx context.Context, criteria *dto.BillCriteria) ([]dto.InvoiceListItem, int64, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []dto.InvoiceListItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.BillCriteria) ([]dto.InvoiceListItem, int64, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.BillCriteria) []dto.InvoiceListItem); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InvoiceListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.BillCriteria) int64); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.BillCriteria) error); ok {
		r2 = rf(ctx, criteria)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBillRepository_FindByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCriteria'
type MockBillRepository_FindByCriteria_Call struct {
	*mock.Call
}

// FindByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.BillCriteria
func (_e *MockBillRepository_Expecter) FindByCriteria(ctx interface{}, criteria interface{}) *MockBillRepository_FindByCriteria_Call {
	return &MockBillRepository_FindByCriteria_Call{Call: _e.mock.On("FindByCriteria", ctx, criteria)}
}

func (_c *MockBillRepository_FindByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.BillCriteria)) *MockBillRepository_FindByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.BillCriteria))
	})
	return _c
}

func (_c *MockBillRepository_FindByCriteria_Call) Return(_a0 []dto.InvoiceListItem, _a1 int64, _a2 error) *MockBillRepository_FindByCriteria_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBillRepository_FindByCriteria_Call) RunAndReturn(run func(context.Context, *dto.BillCriteria) ([]dto.InvoiceListItem, int64, error)) *MockBillRepository_FindByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBillRepository) FindByID(ctx context.Context, id string) (*dto.Bill, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Bill, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Bill); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBillRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBillRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBillRepository_FindByID_Call {
	return &MockBillRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBillRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockBillRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBillRepository_FindByID_Call) Return(_a0 *dto.Bill, _a1 error) *MockBillRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.Bill, error)) *MockBillRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNullDocumentURL provides a mock function with given fields: ctx
func (_m *MockBillRepository) FindByNullDocumentURL(ctx context.Context) ([]*dto.BillWithTascode, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindByNullDocumentURL")
	}

	var r0 []*dto.BillWithTascode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.BillWithTascode, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.BillWithTascode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.BillWithTascode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_FindByNullDocumentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNullDocumentURL'
type MockBillRepository_FindByNullDocumentURL_Call struct {
	*mock.Call
}

// FindByNullDocumentURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillRepository_Expecter) FindByNullDocumentURL(ctx interface{}) *MockBillRepository_FindByNullDocumentURL_Call {
	return &MockBillRepository_FindByNullDocumentURL_Call{Call: _e.mock.On("FindByNullDocumentURL", ctx)}
}

func (_c *MockBillRepository_FindByNullDocumentURL_Call) Run(run func(ctx context.Context)) *MockBillRepository_FindByNullDocumentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBillRepository_FindByNullDocumentURL_Call) Return(_a0 []*dto.BillWithTascode, _a1 error) *MockBillRepository_FindByNullDocumentURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_FindByNullDocumentURL_Call) RunAndReturn(run func(context.Context) ([]*dto.BillWithTascode, error)) *MockBillRepository_FindByNullDocumentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentURL provides a mock function with given fields: ctx, billID, documentURL
func (_m *MockBillRepository) UpdateDocumentURL(ctx context.Context, billID string, documentURL string) error {
	ret := _m.Called(ctx, billID, documentURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, billID, documentURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillRepository_UpdateDocumentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentURL'
type MockBillRepository_UpdateDocumentURL_Call struct {
	*mock.Call
}

// UpdateDocumentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - billID string
//   - documentURL string
func (_e *MockBillRepository_Expecter) UpdateDocumentURL(ctx interface{}, billID interface{}, documentURL interface{}) *MockBillRepository_UpdateDocumentURL_Call {
	return &MockBillRepository_UpdateDocumentURL_Call{Call: _e.mock.On("UpdateDocumentURL", ctx, billID, documentURL)}
}

func (_c *MockBillRepository_UpdateDocumentURL_Call) Run(run func(ctx context.Context, billID string, documentURL string)) *MockBillRepository_UpdateDocumentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockBillRepository_UpdateDocumentURL_Call) Return(_a0 error) *MockBillRepository_UpdateDocumentURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillRepository_UpdateDocumentURL_Call) RunAndReturn(run func(context.Context, string, string) error) *MockBillRepository_UpdateDocumentURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillRepository creates a new instance of MockBillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillRepository {
	mock := &MockBillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
