// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSyncStateRepository is an autogenerated mock type for the SyncStateRepository type
type MockSyncStateRepository struct {
	mock.Mock
}

type MockSyncStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncStateRepository) EXPECT() *MockSyncStateRepository_Expecter {
	return &MockSyncStateRepository_Expecter{mock: &_m.Mock}
}

// AdvancePulledCursor provides a mock function with given fields: ctx, peerNodeID, cursor
func (_m *MockSyncStateRepository) AdvancePulledCursor(ctx context.Context, peerNodeID string, cursor time.Time) error {
	ret := _m.Called(ctx, peerNodeID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for AdvancePulledCursor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, peerNodeID, cursor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncStateRepository_AdvancePulledCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvancePulledCursor'
type MockSyncStateRepository_AdvancePulledCursor_Call struct {
	*mock.Call
}

// AdvancePulledCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - peerNodeID string
//   - cursor time.Time
func (_e *MockSyncStateRepository_Expecter) AdvancePulledCursor(ctx interface{}, peerNodeID interface{}, cursor interface{}) *MockSyncStateRepository_AdvancePulledCursor_Call {
	return &MockSyncStateRepository_AdvancePulledCursor_Call{Call: _e.mock.On("AdvancePulledCursor", ctx, peerNodeID, cursor)}
}

func (_c *MockSyncStateRepository_AdvancePulledCursor_Call) Run(run func(ctx context.Context, peerNodeID string, cursor time.Time)) *MockSyncStateRepository_AdvancePulledCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSyncStateRepository_AdvancePulledCursor_Call) Return(_a0 error) *MockSyncStateRepository_AdvancePulledCursor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncStateRepository_AdvancePulledCursor_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockSyncStateRepository_AdvancePulledCursor_Call {
	_c.Call.Return(run)
	return _c
}

// AdvancePushedSeq provides a mock function with given fields: ctx, peerNodeID, seq
func (_m *MockSyncStateRepository) AdvancePushedSeq(ctx context.Context, peerNodeID string, seq int64) error {
	ret := _m.Called(ctx, peerNodeID, seq)

	if len(ret) == 0 {
		panic("no return value specified for AdvancePushedSeq")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, peerNodeID, seq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncStateRepository_AdvancePushedSeq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvancePushedSeq'
type MockSyncStateRepository_AdvancePushedSeq_Call struct {
	*mock.Call
}

// AdvancePushedSeq is a helper method to define mock.On call
//   - ctx context.Context
//   - peerNodeID string
//   - seq int64
func (_e *MockSyncStateRepository_Expecter) AdvancePushedSeq(ctx interface{}, peerNodeID interface{}, seq interface{}) *MockSyncStateRepository_AdvancePushedSeq_Call {
	return &MockSyncStateRepository_AdvancePushedSeq_Call{Call: _e.mock.On("AdvancePushedSeq", ctx, peerNodeID, seq)}
}

func (_c *MockSyncStateRepository_AdvancePushedSeq_Call) Run(run func(ctx context.Context, peerNodeID string, seq int64)) *MockSyncStateRepository_AdvancePushedSeq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockSyncStateRepository_AdvancePushedSeq_Call) Return(_a0 error) *MockSyncStateRepository_AdvancePushedSeq_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncStateRepository_AdvancePushedSeq_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockSyncStateRepository_AdvancePushedSeq_Call {
	_c.Call.Return(run)
	return _c
}

// GetPulledCursor provides a mock function with given fields: ctx, peerNodeID
func (_m *MockSyncStateRepository) GetPulledCursor(ctx context.Context, peerNodeID string) (*time.Time, error) {
	ret := _m.Called(ctx, peerNodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPulledCursor")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*time.Time, error)); ok {
		return rf(ctx, peerNodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *time.Time); ok {
		r0 = rf(ctx, peerNodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, peerNodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncStateRepository_GetPulledCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPulledCursor'
type MockSyncStateRepository_GetPulledCursor_Call struct {
	*mock.Call
}

// GetPulledCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - peerNodeID string
func (_e *MockSyncStateRepository_Expecter) GetPulledCursor(ctx interface{}, peerNodeID interface{}) *MockSyncStateRepository_GetPulledCursor_Call {
	return &MockSyncStateRepository_GetPulledCursor_Call{Call: _e.mock.On("GetPulledCursor", ctx, peerNodeID)}
}

func (_c *MockSyncStateRepository_GetPulledCursor_Call) Run(run func(ctx context.Context, peerNodeID string)) *MockSyncStateRepository_GetPulledCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSyncStateRepository_GetPulledCursor_Call) Return(_a0 *time.Time, _a1 error) *MockSyncStateRepository_GetPulledCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncStateRepository_GetPulledCursor_Call) RunAndReturn(run func(context.Context, string) (*time.Time, error)) *MockSyncStateRepository_GetPulledCursor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncStateRepository creates a new instance of MockSyncStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncStateRepository {
	mock := &MockSyncStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
