// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockStockMovementEmitter is an autogenerated mock type for the StockMovementEmitter type
type MockStockMovementEmitter struct {
	mock.Mock
}

type MockStockMovementEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockMovementEmitter) EXPECT() *MockStockMovementEmitter_Expecter {
	return &MockStockMovementEmitter_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function with given fields: ctx, movement
func (_m *MockStockMovementEmitter) Emit(ctx context.Context, movement *dto.HistoricStock) error {
	ret := _m.Called(ctx, movement)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.HistoricStock) error); ok {
		r0 = rf(ctx, movement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockMovementEmitter_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type MockStockMovementEmitter_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - movement *dto.HistoricStock
func (_e *MockStockMovementEmitter_Expecter) Emit(ctx interface{}, movement interface{}) *MockStockMovementEmitter_Emit_Call {
	return &MockStockMovementEmitter_Emit_Call{Call: _e.mock.On("Emit", ctx, movement)}
}

func (_c *MockStockMovementEmitter_Emit_Call) Run(run func(ctx context.Context, movement *dto.HistoricStock)) *MockStockMovementEmitter_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.HistoricStock))
	})
	return _c
}

func (_c *MockStockMovementEmitter_Emit_Call) Return(_a0 error) *MockStockMovementEmitter_Emit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockMovementEmitter_Emit_Call) RunAndReturn(run func(context.Context, *dto.HistoricStock) error) *MockStockMovementEmitter_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockMovementEmitter creates a new instance of MockStockMovementEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockMovementEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockMovementEmitter {
	mock := &MockStockMovementEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
