// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockStockRepository is an autogenerated mock type for the StockRepository type
type MockStockRepository struct {
	mock.Mock
}

type MockStockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockRepository) EXPECT() *MockStockRepository_Expecter {
	return &MockStockRepository_Expecter{mock: &_m.Mock}
}

// BulkCreateOrUpdate provides a mock function with given fields: ctx, stocks
func (_m *MockStockRepository) BulkCreateOrUpdate(ctx context.Context, stocks []*dto.Stock) error {
	ret := _m.Called(ctx, stocks)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateOrUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*dto.Stock) error); ok {
		r0 = rf(ctx, stocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_BulkCreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreateOrUpdate'
type MockStockRepository_BulkCreateOrUpdate_Call struct {
	*mock.Call
}

// BulkCreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - stocks []*dto.Stock
func (_e *MockStockRepository_Expecter) BulkCreateOrUpdate(ctx interface{}, stocks interface{}) *MockStockRepository_BulkCreateOrUpdate_Call {
	return &MockStockRepository_BulkCreateOrUpdate_Call{Call: _e.mock.On("BulkCreateOrUpdate", ctx, stocks)}
}

func (_c *MockStockRepository_BulkCreateOrUpdate_Call) Run(run func(ctx context.Context, stocks []*dto.Stock)) *MockStockRepository_BulkCreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*dto.Stock))
	})
	return _c
}

func (_c *MockStockRepository_BulkCreateOrUpdate_Call) Return(_a0 error) *MockStockRepository_BulkCreateOrUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_BulkCreateOrUpdate_Call) RunAndReturn(run func(context.Context, []*dto.Stock) error) *MockStockRepository_BulkCreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, stock
func (_m *MockStockRepository) Create(ctx context.Context, stock *dto.Stock) error {
	ret := _m.Called(ctx, stock)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.Stock) error); ok {
		r0 = rf(ctx, stock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - stock *dto.Stock
func (_e *MockStockRepository_Expecter) Create(ctx interface{}, stock interface{}) *MockStockRepository_Create_Call {
	return &MockStockRepository_Create_Call{Call: _e.mock.On("Create", ctx, stock)}
}

func (_c *MockStockRepository_Create_Call) Run(run func(ctx context.Context, stock *dto.Stock)) *MockStockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.Stock))
	})
	return _c
}

func (_c *MockStockRepository_Create_Call) Return(_a0 error) *MockStockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_Create_Call) RunAndReturn(run func(context.Context, *dto.Stock) error) *MockStockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHistoricRecord provides a mock function with given fields: ctx, historicStock
func (_m *MockStockRepository) CreateHistoricRecord(ctx context.Context, historicStock *dto.HistoricStock) error {
	ret := _m.Called(ctx, historicStock)

	if len(ret) == 0 {
		panic("no return value specified for CreateHistoricRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.HistoricStock) error); ok {
		r0 = rf(ctx, historicStock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_CreateHistoricRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHistoricRecord'
type MockStockRepository_CreateHistoricRecord_Call struct {
	*mock.Call
}

// CreateHistoricRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - historicStock *dto.HistoricStock
func (_e *MockStockRepository_Expecter) CreateHistoricRecord(ctx interface{}, historicStock interface{}) *MockStockRepository_CreateHistoricRecord_Call {
	return &MockStockRepository_CreateHistoricRecord_Call{Call: _e.mock.On("CreateHistoricRecord", ctx, historicStock)}
}

func (_c *MockStockRepository_CreateHistoricRecord_Call) Run(run func(ctx context.Context, historicStock *dto.HistoricStock)) *MockStockRepository_CreateHistoricRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.HistoricStock))
	})
	return _c
}

func (_c *MockStockRepository_CreateHistoricRecord_Call) Return(_a0 error) *MockStockRepository_CreateHistoricRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_CreateHistoricRecord_Call) RunAndReturn(run func(context.Context, *dto.HistoricStock) error) *MockStockRepository_CreateHistoricRecord_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, productID
func (_m *MockStockRepository) Delete(ctx context.Context, productID string) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockStockRepository_Expecter) Delete(ctx interface{}, productID interface{}) *MockStockRepository_Delete_Call {
	return &MockStockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, productID)}
}

func (_c *MockStockRepository_Delete_Call) Run(run func(ctx context.Context, productID string)) *MockStockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStockRepository_Delete_Call) Return(_a0 error) *MockStockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockStockRepository) FindAll(ctx context.Context) ([]*dto.Stock, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.Stock, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.Stock); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockStockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStockRepository_Expecter) FindAll(ctx interface{}) *MockStockRepository_FindAll_Call {
	return &MockStockRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockStockRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockStockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStockRepository_FindAll_Call) Return(_a0 []*dto.Stock, _a1 error) *MockStockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.Stock, error)) *MockStockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProductID provides a mock function with given fields: ctx, productID
func (_m *MockStockRepository) FindByProductID(ctx context.Context, productID string) (*dto.Stock, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProductID")
	}

	var r0 *dto.Stock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Stock, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Stock); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Stock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockRepository_FindByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProductID'
type MockStockRepository_FindByProductID_Call struct {
	*mock.Call
}

// FindByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockStockRepository_Expecter) FindByProductID(ctx interface{}, productID interface{}) *MockStockRepository_FindByProductID_Call {
	return &MockStockRepository_FindByProductID_Call{Call: _e.mock.On("FindByProductID", ctx, productID)}
}

func (_c *MockStockRepository_FindByProductID_Call) Run(run func(ctx context.Context, productID string)) *MockStockRepository_FindByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStockRepository_FindByProductID_Call) Return(_a0 *dto.Stock, _a1 error) *MockStockRepository_FindByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockRepository_FindByProductID_Call) RunAndReturn(run func(context.Context, string) (*dto.Stock, error)) *MockStockRepository_FindByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// FindHistoricByProductID provides a mock function with given fields: ctx, productID
func (_m *MockStockRepository) FindHistoricByProductID(ctx context.Context, productID string) ([]*dto.HistoricStock, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindHistoricByProductID")
	}

	var r0 []*dto.HistoricStock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.HistoricStock, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.HistoricStock); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.HistoricStock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockRepository_FindHistoricByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindHistoricByProductID'
type MockStockRepository_FindHistoricByProductID_Call struct {
	*mock.Call
}

// FindHistoricByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockStockRepository_Expecter) FindHistoricByProductID(ctx interface{}, productID interface{}) *MockStockRepository_FindHistoricByProductID_Call {
	return &MockStockRepository_FindHistoricByProductID_Call{Call: _e.mock.On("FindHistoricByProductID", ctx, productID)}
}

func (_c *MockStockRepository_FindHistoricByProductID_Call) Run(run func(ctx context.Context, productID string)) *MockStockRepository_FindHistoricByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStockRepository_FindHistoricByProductID_Call) Return(_a0 []*dto.HistoricStock, _a1 error) *MockStockRepository_FindHistoricByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockRepository_FindHistoricByProductID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.HistoricStock, error)) *MockStockRepository_FindHistoricByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAmount provides a mock function with given fields: ctx, productID, amount
func (_m *MockStockRepository) UpdateAmount(ctx context.Context, productID string, amount int) error {
	ret := _m.Called(ctx, productID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAmount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, productID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockRepository_UpdateAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAmount'
type MockStockRepository_UpdateAmount_Call struct {
	*mock.Call
}

// UpdateAmount is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - amount int
func (_e *MockStockRepository_Expecter) UpdateAmount(ctx interface{}, productID interface{}, amount interface{}) *MockStockRepository_UpdateAmount_Call {
	return &MockStockRepository_UpdateAmount_Call{Call: _e.mock.On("UpdateAmount", ctx, productID, amount)}
}

func (_c *MockStockRepository_UpdateAmount_Call) Run(run func(ctx context.Context, productID string, amount int)) *MockStockRepository_UpdateAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockStockRepository_UpdateAmount_Call) Return(_a0 error) *MockStockRepository_UpdateAmount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockRepository_UpdateAmount_Call) RunAndReturn(run func(context.Context, string, int) error) *MockStockRepository_UpdateAmount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockRepository creates a new instance of MockStockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockRepository {
	mock := &MockStockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
