// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRoleRepository is an autogenerated mock type for the UserRoleRepository type
type MockUserRoleRepository struct {
	mock.Mock
}

type MockUserRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRoleRepository) EXPECT() *MockUserRoleRepository_Expecter {
	return &MockUserRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userRole
func (_m *MockUserRoleRepository) Create(ctx context.Context, userRole *dto.UserRole) error {
	ret := _m.Called(ctx, userRole)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UserRole) error); ok {
		r0 = rf(ctx, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userRole *dto.UserRole
func (_e *MockUserRoleRepository_Expecter) Create(ctx interface{}, userRole interface{}) *MockUserRoleRepository_Create_Call {
	return &MockUserRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, userRole)}
}

func (_c *MockUserRoleRepository_Create_Call) Run(run func(ctx context.Context, userRole *dto.UserRole)) *MockUserRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.UserRole))
	})
	return _c
}

func (_c *MockUserRoleRepository_Create_Call) Return(_a0 error) *MockUserRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *dto.UserRole) error) *MockUserRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserRoleRepository) FindByUserID(ctx context.Context, userID string) ([]*dto.UserRole, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*dto.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.UserRole, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.UserRole); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRoleRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockUserRoleRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRoleRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockUserRoleRepository_FindByUserID_Call {
	return &MockUserRoleRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockUserRoleRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRoleRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRoleRepository_FindByUserID_Call) Return(_a0 []*dto.UserRole, _a1 error) *MockUserRoleRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRoleRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.UserRole, error)) *MockUserRoleRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRolesByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserRoleRepository) FindRolesByUserID(ctx context.Context, userID string) ([]*dto.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindRolesByUserID")
	}

	var r0 []*dto.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRoleRepository_FindRolesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRolesByUserID'
type MockUserRoleRepository_FindRolesByUserID_Call struct {
	*mock.Call
}

// FindRolesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRoleRepository_Expecter) FindRolesByUserID(ctx interface{}, userID interface{}) *MockUserRoleRepository_FindRolesByUserID_Call {
	return &MockUserRoleRepository_FindRolesByUserID_Call{Call: _e.mock.On("FindRolesByUserID", ctx, userID)}
}

func (_c *MockUserRoleRepository_FindRolesByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRoleRepository_FindRolesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRoleRepository_FindRolesByUserID_Call) Return(_a0 []*dto.Role, _a1 error) *MockUserRoleRepository_FindRolesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRoleRepository_FindRolesByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.Role, error)) *MockUserRoleRepository_FindRolesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRoleRepository creates a new instance of MockUserRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRoleRepository {
	mock := &MockUserRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
