// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	expense "laguna-escondida/backend/internal/domain/aggregate/expense"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockExpenseRepository) Create(ctx context.Context, _a1 *expense.Aggregate) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *expense.Aggregate) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *expense.Aggregate
func (_e *MockExpenseRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockExpenseRepository_Create_Call {
	return &MockExpenseRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockExpenseRepository_Create_Call) Run(run func(ctx context.Context, _a1 *expense.Aggregate)) *MockExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*expense.Aggregate))
	})
	return _c
}

func (_c *MockExpenseRepository_Create_Call) Return(_a0 error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Create_Call) RunAndReturn(run func(context.Context, *expense.Aggregate) error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockExpenseRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExpenseRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockExpenseRepository_Delete_Call {
	return &MockExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockExpenseRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) Return(_a0 error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockExpenseRepository) FindAll(ctx context.Context) ([]*dto.ExpenseWithCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.ExpenseWithCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.ExpenseWithCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.ExpenseWithCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExpenseWithCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockExpenseRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExpenseRepository_Expecter) FindAll(ctx interface{}) *MockExpenseRepository_FindAll_Call {
	return &MockExpenseRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockExpenseRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockExpenseRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockExpenseRepository_FindAll_Call) Return(_a0 []*dto.ExpenseWithCategory, _a1 error) *MockExpenseRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.ExpenseWithCategory, error)) *MockExpenseRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockExpenseRepository) FindByCriteria(ctx context.Context, criteria *dto.ExpenseListCriteria) ([]*dto.ExpenseWithCategory, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []*dto.ExpenseWithCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ExpenseListCriteria) ([]*dto.ExpenseWithCategory, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ExpenseListCriteria) []*dto.ExpenseWithCategory); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExpenseWithCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ExpenseListCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_FindByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCriteria'
type MockExpenseRepository_FindByCriteria_Call struct {
	*mock.Call
}

// FindByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.ExpenseListCriteria
func (_e *MockExpenseRepository_Expecter) FindByCriteria(ctx interface{}, criteria interface{}) *MockExpenseRepository_FindByCriteria_Call {
	return &MockExpenseRepository_FindByCriteria_Call{Call: _e.mock.On("FindByCriteria", ctx, criteria)}
}

func (_c *MockExpenseRepository_FindByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.ExpenseListCriteria)) *MockExpenseRepository_FindByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.ExpenseListCriteria))
	})
	return _c
}

func (_c *MockExpenseRepository_FindByCriteria_Call) Return(_a0 []*dto.ExpenseWithCategory, _a1 error) *MockExpenseRepository_FindByCriteria_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_FindByCriteria_Call) RunAndReturn(run func(context.Context, *dto.ExpenseListCriteria) ([]*dto.ExpenseWithCategory, error)) *MockExpenseRepository_FindByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockExpenseRepository) FindByID(ctx context.Context, id string) (*dto.ExpenseWithCategory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.ExpenseWithCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ExpenseWithCategory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ExpenseWithCategory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseWithCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockExpenseRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExpenseRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockExpenseRepository_FindByID_Call {
	return &MockExpenseRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockExpenseRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockExpenseRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpenseRepository_FindByID_Call) Return(_a0 *dto.ExpenseWithCategory, _a1 error) *MockExpenseRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.ExpenseWithCategory, error)) *MockExpenseRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseSummary provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockExpenseRepository) GetExpenseSummary(ctx context.Context, startDate time.Time, endDate time.Time) (*dto.ExpenseSummary, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseSummary")
	}

	var r0 *dto.ExpenseSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*dto.ExpenseSummary, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *dto.ExpenseSummary); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExpenseSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpenseRepository_GetExpenseSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseSummary'
type MockExpenseRepository_GetExpenseSummary_Call struct {
	*mock.Call
}

// GetExpenseSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockExpenseRepository_Expecter) GetExpenseSummary(ctx interface{}, startDate interface{}, endDate interface{}) *MockExpenseRepository_GetExpenseSummary_Call {
	return &MockExpenseRepository_GetExpenseSummary_Call{Call: _e.mock.On("GetExpenseSummary", ctx, startDate, endDate)}
}

func (_c *MockExpenseRepository_GetExpenseSummary_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time)) *MockExpenseRepository_GetExpenseSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockExpenseRepository_GetExpenseSummary_Call) Return(_a0 *dto.ExpenseSummary, _a1 error) *MockExpenseRepository_GetExpenseSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpenseRepository_GetExpenseSummary_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (*dto.ExpenseSummary, error)) *MockExpenseRepository_GetExpenseSummary_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *MockExpenseRepository) Update(ctx context.Context, id string, _a2 *expense.Aggregate) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *expense.Aggregate) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - _a2 *expense.Aggregate
func (_e *MockExpenseRepository_Expecter) Update(ctx interface{}, id interface{}, _a2 interface{}) *MockExpenseRepository_Update_Call {
	return &MockExpenseRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, _a2)}
}

func (_c *MockExpenseRepository_Update_Call) Run(run func(ctx context.Context, id string, _a2 *expense.Aggregate)) *MockExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*expense.Aggregate))
	})
	return _c
}

func (_c *MockExpenseRepository_Update_Call) Return(_a0 error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_Update_Call) RunAndReturn(run func(context.Context, string, *expense.Aggregate) error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStoragePaths provides a mock function with given fields: ctx, id, pdfPath, xmlPath
func (_m *MockExpenseRepository) UpdateStoragePaths(ctx context.Context, id string, pdfPath *string, xmlPath *string) error {
	ret := _m.Called(ctx, id, pdfPath, xmlPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStoragePaths")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) error); ok {
		r0 = rf(ctx, id, pdfPath, xmlPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpenseRepository_UpdateStoragePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStoragePaths'
type MockExpenseRepository_UpdateStoragePaths_Call struct {
	*mock.Call
}

// UpdateStoragePaths is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - pdfPath *string
//   - xmlPath *string
func (_e *MockExpenseRepository_Expecter) UpdateStoragePaths(ctx interface{}, id interface{}, pdfPath interface{}, xmlPath interface{}) *MockExpenseRepository_UpdateStoragePaths_Call {
	return &MockExpenseRepository_UpdateStoragePaths_Call{Call: _e.mock.On("UpdateStoragePaths", ctx, id, pdfPath, xmlPath)}
}

func (_c *MockExpenseRepository_UpdateStoragePaths_Call) Run(run func(ctx context.Context, id string, pdfPath *string, xmlPath *string)) *MockExpenseRepository_UpdateStoragePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockExpenseRepository_UpdateStoragePaths_Call) Return(_a0 error) *MockExpenseRepository_UpdateStoragePaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpenseRepository_UpdateStoragePaths_Call) RunAndReturn(run func(context.Context, string, *string, *string) error) *MockExpenseRepository_UpdateStoragePaths_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
