// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSyncStockPullClient is an autogenerated mock type for the SyncStockPullClient type
type MockSyncStockPullClient struct {
	mock.Mock
}

type MockSyncStockPullClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncStockPullClient) EXPECT() *MockSyncStockPullClient_Expecter {
	return &MockSyncStockPullClient_Expecter{mock: &_m.Mock}
}

// PullStock provides a mock function with given fields: ctx, since
func (_m *MockSyncStockPullClient) PullStock(ctx context.Context, since time.Time) (*dto.SyncStockPullResponse, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for PullStock")
	}

	var r0 *dto.SyncStockPullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*dto.SyncStockPullResponse, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *dto.SyncStockPullResponse); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SyncStockPullResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncStockPullClient_PullStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullStock'
type MockSyncStockPullClient_PullStock_Call struct {
	*mock.Call
}

// PullStock is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSyncStockPullClient_Expecter) PullStock(ctx interface{}, since interface{}) *MockSyncStockPullClient_PullStock_Call {
	return &MockSyncStockPullClient_PullStock_Call{Call: _e.mock.On("PullStock", ctx, since)}
}

func (_c *MockSyncStockPullClient_PullStock_Call) Run(run func(ctx context.Context, since time.Time)) *MockSyncStockPullClient_PullStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSyncStockPullClient_PullStock_Call) Return(_a0 *dto.SyncStockPullResponse, _a1 error) *MockSyncStockPullClient_PullStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncStockPullClient_PullStock_Call) RunAndReturn(run func(context.Context, time.Time) (*dto.SyncStockPullResponse, error)) *MockSyncStockPullClient_PullStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncStockPullClient creates a new instance of MockSyncStockPullClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncStockPullClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncStockPullClient {
	mock := &MockSyncStockPullClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
