// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockStorageClient) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorageClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) Delete(ctx interface{}, key interface{}) *MockStorageClient_Delete_Call {
	return &MockStorageClient_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockStorageClient_Delete_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageClient_Delete_Call) Return(_a0 error) *MockStorageClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, key
func (_m *MockStorageClient) Download(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageClient_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStorageClient_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) Download(ctx interface{}, key interface{}) *MockStorageClient_Download_Call {
	return &MockStorageClient_Download_Call{Call: _e.mock.On("Download", ctx, key)}
}

func (_c *MockStorageClient_Download_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageClient_Download_Call) Return(_a0 []byte, _a1 error) *MockStorageClient_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageClient_Download_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockStorageClient_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function with given fields: ctx, key, expiration
func (_m *MockStorageClient) GetPresignedURL(ctx context.Context, key string, expiration time.Duration) (string, error) {
	ret := _m.Called(ctx, key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, expiration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, expiration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageClient_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockStorageClient_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiration time.Duration
func (_e *MockStorageClient_Expecter) GetPresignedURL(ctx interface{}, key interface{}, expiration interface{}) *MockStorageClient_GetPresignedURL_Call {
	return &MockStorageClient_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, key, expiration)}
}

func (_c *MockStorageClient_GetPresignedURL_Call) Run(run func(ctx context.Context, key string, expiration time.Duration)) *MockStorageClient_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockStorageClient_GetPresignedURL_Call) Return(_a0 string, _a1 error) *MockStorageClient_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageClient_GetPresignedURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockStorageClient_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicURL provides a mock function with given fields: key
func (_m *MockStorageClient) GetPublicURL(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorageClient_GetPublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicURL'
type MockStorageClient_GetPublicURL_Call struct {
	*mock.Call
}

// GetPublicURL is a helper method to define mock.On call
//   - key string
func (_e *MockStorageClient_Expecter) GetPublicURL(key interface{}) *MockStorageClient_GetPublicURL_Call {
	return &MockStorageClient_GetPublicURL_Call{Call: _e.mock.On("GetPublicURL", key)}
}

func (_c *MockStorageClient_GetPublicURL_Call) Run(run func(key string)) *MockStorageClient_GetPublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorageClient_GetPublicURL_Call) Return(_a0 string) *MockStorageClient_GetPublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_GetPublicURL_Call) RunAndReturn(run func(string) string) *MockStorageClient_GetPublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, data, contentType
func (_m *MockStorageClient) Upload(ctx context.Context, key string, data []byte, contentType string) error {
	ret := _m.Called(ctx, key, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = rf(ctx, key, data, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorageClient_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - contentType string
func (_e *MockStorageClient_Expecter) Upload(ctx interface{}, key interface{}, data interface{}, contentType interface{}) *MockStorageClient_Upload_Call {
	return &MockStorageClient_Upload_Call{Call: _e.mock.On("Upload", ctx, key, data, contentType)}
}

func (_c *MockStorageClient_Upload_Call) Run(run func(ctx context.Context, key string, data []byte, contentType string)) *MockStorageClient_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockStorageClient_Upload_Call) Return(_a0 error) *MockStorageClient_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_Upload_Call) RunAndReturn(run func(context.Context, string, []byte, string) error) *MockStorageClient_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
