// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockReceiptPrinter is an autogenerated mock type for the ReceiptPrinter type
type MockReceiptPrinter struct {
	mock.Mock
}

type MockReceiptPrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiptPrinter) EXPECT() *MockReceiptPrinter_Expecter {
	return &MockReceiptPrinter_Expecter{mock: &_m.Mock}
}

// Print provides a mock function with given fields: ctx, ticket
func (_m *MockReceiptPrinter) Print(ctx context.Context, ticket *dto.Ticket) error {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Print")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.Ticket) error); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReceiptPrinter_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockReceiptPrinter_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *dto.Ticket
func (_e *MockReceiptPrinter_Expecter) Print(ctx interface{}, ticket interface{}) *MockReceiptPrinter_Print_Call {
	return &MockReceiptPrinter_Print_Call{Call: _e.mock.On("Print", ctx, ticket)}
}

func (_c *MockReceiptPrinter_Print_Call) Run(run func(ctx context.Context, ticket *dto.Ticket)) *MockReceiptPrinter_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.Ticket))
	})
	return _c
}

func (_c *MockReceiptPrinter_Print_Call) Return(_a0 error) *MockReceiptPrinter_Print_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReceiptPrinter_Print_Call) RunAndReturn(run func(context.Context, *dto.Ticket) error) *MockReceiptPrinter_Print_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReceiptPrinter creates a new instance of MockReceiptPrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiptPrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiptPrinter {
	mock := &MockReceiptPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
