// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockElectronicInvoiceClient is an autogenerated mock type for the ElectronicInvoiceClient type
type MockElectronicInvoiceClient struct {
	mock.Mock
}

type MockElectronicInvoiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockElectronicInvoiceClient) EXPECT() *MockElectronicInvoiceClient_Expecter {
	return &MockElectronicInvoiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockElectronicInvoiceClient) Create(ctx context.Context, req *dto.CreateElectronicInvoiceRequest) (*dto.CreateElectronicInvoiceResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CreateElectronicInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateElectronicInvoiceRequest) (*dto.CreateElectronicInvoiceResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateElectronicInvoiceRequest) *dto.CreateElectronicInvoiceResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateElectronicInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateElectronicInvoiceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElectronicInvoiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockElectronicInvoiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateElectronicInvoiceRequest
func (_e *MockElectronicInvoiceClient_Expecter) Create(ctx interface{}, req interface{}) *MockElectronicInvoiceClient_Create_Call {
	return &MockElectronicInvoiceClient_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockElectronicInvoiceClient_Create_Call) Run(run func(ctx context.Context, req *dto.CreateElectronicInvoiceRequest)) *MockElectronicInvoiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CreateElectronicInvoiceRequest))
	})
	return _c
}

func (_c *MockElectronicInvoiceClient_Create_Call) Return(_a0 *dto.CreateElectronicInvoiceResponse, _a1 error) *MockElectronicInvoiceClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElectronicInvoiceClient_Create_Call) RunAndReturn(run func(context.Context, *dto.CreateElectronicInvoiceRequest) (*dto.CreateElectronicInvoiceResponse, error)) *MockElectronicInvoiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSupportDocument provides a mock function with given fields: ctx, req
func (_m *MockElectronicInvoiceClient) CreateSupportDocument(ctx context.Context, req *dto.CreateSupportDocumentRequest) (*dto.CreateSupportDocumentResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupportDocument")
	}

	var r0 *dto.CreateSupportDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateSupportDocumentRequest) (*dto.CreateSupportDocumentResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateSupportDocumentRequest) *dto.CreateSupportDocumentResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateSupportDocumentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateSupportDocumentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElectronicInvoiceClient_CreateSupportDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSupportDocument'
type MockElectronicInvoiceClient_CreateSupportDocument_Call struct {
	*mock.Call
}

// CreateSupportDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateSupportDocumentRequest
func (_e *MockElectronicInvoiceClient_Expecter) CreateSupportDocument(ctx interface{}, req interface{}) *MockElectronicInvoiceClient_CreateSupportDocument_Call {
	return &MockElectronicInvoiceClient_CreateSupportDocument_Call{Call: _e.mock.On("CreateSupportDocument", ctx, req)}
}

func (_c *MockElectronicInvoiceClient_CreateSupportDocument_Call) Run(run func(ctx context.Context, req *dto.CreateSupportDocumentRequest)) *MockElectronicInvoiceClient_CreateSupportDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CreateSupportDocumentRequest))
	})
	return _c
}

func (_c *MockElectronicInvoiceClient_CreateSupportDocument_Call) Return(_a0 *dto.CreateSupportDocumentResponse, _a1 error) *MockElectronicInvoiceClient_CreateSupportDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElectronicInvoiceClient_CreateSupportDocument_Call) RunAndReturn(run func(context.Context, *dto.CreateSupportDocumentRequest) (*dto.CreateSupportDocumentResponse, error)) *MockElectronicInvoiceClient_CreateSupportDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, tascode
func (_m *MockElectronicInvoiceClient) Get(ctx context.Context, tascode string) (*dto.VerifyInvoiceStatusResponse, error) {
	ret := _m.Called(ctx, tascode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.VerifyInvoiceStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.VerifyInvoiceStatusResponse, error)); ok {
		return rf(ctx, tascode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.VerifyInvoiceStatusResponse); ok {
		r0 = rf(ctx, tascode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VerifyInvoiceStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tascode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockElectronicInvoiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockElectronicInvoiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tascode string
func (_e *MockElectronicInvoiceClient_Expecter) Get(ctx interface{}, tascode interface{}) *MockElectronicInvoiceClient_Get_Call {
	return &MockElectronicInvoiceClient_Get_Call{Call: _e.mock.On("Get", ctx, tascode)}
}

func (_c *MockElectronicInvoiceClient_Get_Call) Run(run func(ctx context.Context, tascode string)) *MockElectronicInvoiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockElectronicInvoiceClient_Get_Call) Return(_a0 *dto.VerifyInvoiceStatusResponse, _a1 error) *MockElectronicInvoiceClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockElectronicInvoiceClient_Get_Call) RunAndReturn(run func(context.Context, string) (*dto.VerifyInvoiceStatusResponse, error)) *MockElectronicInvoiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockElectronicInvoiceClient creates a new instance of MockElectronicInvoiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockElectronicInvoiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockElectronicInvoiceClient {
	mock := &MockElectronicInvoiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
