// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSyncPullClient is an autogenerated mock type for the SyncPullClient type
type MockSyncPullClient struct {
	mock.Mock
}

type MockSyncPullClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncPullClient) EXPECT() *MockSyncPullClient_Expecter {
	return &MockSyncPullClient_Expecter{mock: &_m.Mock}
}

// Pull provides a mock function with given fields: ctx, since
func (_m *MockSyncPullClient) Pull(ctx context.Context, since time.Time) (*dto.SyncPullResponse, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 *dto.SyncPullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*dto.SyncPullResponse, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *dto.SyncPullResponse); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SyncPullResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncPullClient_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockSyncPullClient_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSyncPullClient_Expecter) Pull(ctx interface{}, since interface{}) *MockSyncPullClient_Pull_Call {
	return &MockSyncPullClient_Pull_Call{Call: _e.mock.On("Pull", ctx, since)}
}

func (_c *MockSyncPullClient_Pull_Call) Run(run func(ctx context.Context, since time.Time)) *MockSyncPullClient_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSyncPullClient_Pull_Call) Return(_a0 *dto.SyncPullResponse, _a1 error) *MockSyncPullClient_Pull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncPullClient_Pull_Call) RunAndReturn(run func(context.Context, time.Time) (*dto.SyncPullResponse, error)) *MockSyncPullClient_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncPullClient creates a new instance of MockSyncPullClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncPullClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncPullClient {
	mock := &MockSyncPullClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
