// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	open_bill "laguna-escondida/backend/internal/domain/aggregate/open_bill"
)

// MockOpenBillRepository is an autogenerated mock type for the OpenBillRepository type
type MockOpenBillRepository struct {
	mock.Mock
}

type MockOpenBillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenBillRepository) EXPECT() *MockOpenBillRepository_Expecter {
	return &MockOpenBillRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, aggregate
func (_m *MockOpenBillRepository) Create(ctx context.Context, aggregate *open_bill.Aggregate) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *open_bill.Aggregate) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenBillRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOpenBillRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *open_bill.Aggregate
func (_e *MockOpenBillRepository_Expecter) Create(ctx interface{}, aggregate interface{}) *MockOpenBillRepository_Create_Call {
	return &MockOpenBillRepository_Create_Call{Call: _e.mock.On("Create", ctx, aggregate)}
}

func (_c *MockOpenBillRepository_Create_Call) Run(run func(ctx context.Context, aggregate *open_bill.Aggregate)) *MockOpenBillRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*open_bill.Aggregate))
	})
	return _c
}

func (_c *MockOpenBillRepository_Create_Call) Return(_a0 error) *MockOpenBillRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenBillRepository_Create_Call) RunAndReturn(run func(context.Context, *open_bill.Aggregate) error) *MockOpenBillRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, openBillID
func (_m *MockOpenBillRepository) Delete(ctx context.Context, openBillID string) error {
	ret := _m.Called(ctx, openBillID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, openBillID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenBillRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOpenBillRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - openBillID string
func (_e *MockOpenBillRepository_Expecter) Delete(ctx interface{}, openBillID interface{}) *MockOpenBillRepository_Delete_Call {
	return &MockOpenBillRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, openBillID)}
}

func (_c *MockOpenBillRepository_Delete_Call) Run(run func(ctx context.Context, openBillID string)) *MockOpenBillRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOpenBillRepository_Delete_Call) Return(_a0 error) *MockOpenBillRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenBillRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockOpenBillRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAggregateByID provides a mock function with given fields: ctx, id
func (_m *MockOpenBillRepository) FindAggregateByID(ctx context.Context, id string) (*open_bill.Aggregate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindAggregateByID")
	}

	var r0 *open_bill.Aggregate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*open_bill.Aggregate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *open_bill.Aggregate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*open_bill.Aggregate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpenBillRepository_FindAggregateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAggregateByID'
type MockOpenBillRepository_FindAggregateByID_Call struct {
	*mock.Call
}

// FindAggregateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOpenBillRepository_Expecter) FindAggregateByID(ctx interface{}, id interface{}) *MockOpenBillRepository_FindAggregateByID_Call {
	return &MockOpenBillRepository_FindAggregateByID_Call{Call: _e.mock.On("FindAggregateByID", ctx, id)}
}

func (_c *MockOpenBillRepository_FindAggregateByID_Call) Run(run func(ctx context.Context, id string)) *MockOpenBillRepository_FindAggregateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOpenBillRepository_FindAggregateByID_Call) Return(_a0 *open_bill.Aggregate, _a1 error) *MockOpenBillRepository_FindAggregateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpenBillRepository_FindAggregateByID_Call) RunAndReturn(run func(context.Context, string) (*open_bill.Aggregate, error)) *MockOpenBillRepository_FindAggregateByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockOpenBillRepository) FindAll(ctx context.Context) ([]*dto.OpenBillWithCreator, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.OpenBillWithCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.OpenBillWithCreator, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.OpenBillWithCreator); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.OpenBillWithCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpenBillRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockOpenBillRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOpenBillRepository_Expecter) FindAll(ctx interface{}) *MockOpenBillRepository_FindAll_Call {
	return &MockOpenBillRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockOpenBillRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockOpenBillRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOpenBillRepository_FindAll_Call) Return(_a0 []*dto.OpenBillWithCreator, _a1 error) *MockOpenBillRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpenBillRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.OpenBillWithCreator, error)) *MockOpenBillRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockOpenBillRepository) FindByID(ctx context.Context, id string) (*dto.OpenBillWithProducts, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.OpenBillWithProducts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OpenBillWithProducts, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OpenBillWithProducts); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OpenBillWithProducts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpenBillRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOpenBillRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOpenBillRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOpenBillRepository_FindByID_Call {
	return &MockOpenBillRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOpenBillRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockOpenBillRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOpenBillRepository_FindByID_Call) Return(_a0 *dto.OpenBillWithProducts, _a1 error) *MockOpenBillRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpenBillRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.OpenBillWithProducts, error)) *MockOpenBillRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithProducts provides a mock function with given fields: ctx, id
func (_m *MockOpenBillRepository) FindByIDWithProducts(ctx context.Context, id string) (*dto.OpenBillWithProducts, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithProducts")
	}

	var r0 *dto.OpenBillWithProducts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.OpenBillWithProducts, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.OpenBillWithProducts); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OpenBillWithProducts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpenBillRepository_FindByIDWithProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithProducts'
type MockOpenBillRepository_FindByIDWithProducts_Call struct {
	*mock.Call
}

// FindByIDWithProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOpenBillRepository_Expecter) FindByIDWithProducts(ctx interface{}, id interface{}) *MockOpenBillRepository_FindByIDWithProducts_Call {
	return &MockOpenBillRepository_FindByIDWithProducts_Call{Call: _e.mock.On("FindByIDWithProducts", ctx, id)}
}

func (_c *MockOpenBillRepository_FindByIDWithProducts_Call) Run(run func(ctx context.Context, id string)) *MockOpenBillRepository_FindByIDWithProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOpenBillRepository_FindByIDWithProducts_Call) Return(_a0 *dto.OpenBillWithProducts, _a1 error) *MockOpenBillRepository_FindByIDWithProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpenBillRepository_FindByIDWithProducts_Call) RunAndReturn(run func(context.Context, string) (*dto.OpenBillWithProducts, error)) *MockOpenBillRepository_FindByIDWithProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, aggregate
func (_m *MockOpenBillRepository) Update(ctx context.Context, aggregate *open_bill.Aggregate) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *open_bill.Aggregate) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenBillRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOpenBillRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate *open_bill.Aggregate
func (_e *MockOpenBillRepository_Expecter) Update(ctx interface{}, aggregate interface{}) *MockOpenBillRepository_Update_Call {
	return &MockOpenBillRepository_Update_Call{Call: _e.mock.On("Update", ctx, aggregate)}
}

func (_c *MockOpenBillRepository_Update_Call) Run(run func(ctx context.Context, aggregate *open_bill.Aggregate)) *MockOpenBillRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*open_bill.Aggregate))
	})
	return _c
}

func (_c *MockOpenBillRepository_Update_Call) Return(_a0 error) *MockOpenBillRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenBillRepository_Update_Call) RunAndReturn(run func(context.Context, *open_bill.Aggregate) error) *MockOpenBillRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOpenBillRepository creates a new instance of MockOpenBillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenBillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenBillRepository {
	mock := &MockOpenBillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
