// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncApplier is an autogenerated mock type for the SyncApplier type
type MockSyncApplier struct {
	mock.Mock
}

type MockSyncApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncApplier) EXPECT() *MockSyncApplier_Expecter {
	return &MockSyncApplier_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, op
func (_m *MockSyncApplier) Apply(ctx context.Context, op *dto.SyncOutboxEntry) error {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SyncOutboxEntry) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncApplier_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockSyncApplier_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - op *dto.SyncOutboxEntry
func (_e *MockSyncApplier_Expecter) Apply(ctx interface{}, op interface{}) *MockSyncApplier_Apply_Call {
	return &MockSyncApplier_Apply_Call{Call: _e.mock.On("Apply", ctx, op)}
}

func (_c *MockSyncApplier_Apply_Call) Run(run func(ctx context.Context, op *dto.SyncOutboxEntry)) *MockSyncApplier_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SyncOutboxEntry))
	})
	return _c
}

func (_c *MockSyncApplier_Apply_Call) Return(_a0 error) *MockSyncApplier_Apply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncApplier_Apply_Call) RunAndReturn(run func(context.Context, *dto.SyncOutboxEntry) error) *MockSyncApplier_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncApplier creates a new instance of MockSyncApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncApplier {
	mock := &MockSyncApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
