// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	customer "laguna-escondida/backend/internal/domain/aggregate/customer"

	mock "github.com/stretchr/testify/mock"
)

// MockBillOwnerRepository is an autogenerated mock type for the BillOwnerRepository type
type MockBillOwnerRepository struct {
	mock.Mock
}

type MockBillOwnerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillOwnerRepository) EXPECT() *MockBillOwnerRepository_Expecter {
	return &MockBillOwnerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockBillOwnerRepository) Create(ctx context.Context, _a1 *customer.Aggregate) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customer.Aggregate) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillOwnerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillOwnerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *customer.Aggregate
func (_e *MockBillOwnerRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockBillOwnerRepository_Create_Call {
	return &MockBillOwnerRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockBillOwnerRepository_Create_Call) Run(run func(ctx context.Context, _a1 *customer.Aggregate)) *MockBillOwnerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customer.Aggregate))
	})
	return _c
}

func (_c *MockBillOwnerRepository_Create_Call) Return(_a0 error) *MockBillOwnerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillOwnerRepository_Create_Call) RunAndReturn(run func(context.Context, *customer.Aggregate) error) *MockBillOwnerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBillOwnerRepository) FindByID(ctx context.Context, id string) (*customer.Aggregate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *customer.Aggregate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*customer.Aggregate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *customer.Aggregate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Aggregate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillOwnerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBillOwnerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBillOwnerRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBillOwnerRepository_FindByID_Call {
	return &MockBillOwnerRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBillOwnerRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockBillOwnerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBillOwnerRepository_FindByID_Call) Return(_a0 *customer.Aggregate, _a1 error) *MockBillOwnerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillOwnerRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*customer.Aggregate, error)) *MockBillOwnerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockBillOwnerRepository) Update(ctx context.Context, _a1 *customer.Aggregate) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *customer.Aggregate) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillOwnerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBillOwnerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *customer.Aggregate
func (_e *MockBillOwnerRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockBillOwnerRepository_Update_Call {
	return &MockBillOwnerRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockBillOwnerRepository_Update_Call) Run(run func(ctx context.Context, _a1 *customer.Aggregate)) *MockBillOwnerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*customer.Aggregate))
	})
	return _c
}

func (_c *MockBillOwnerRepository_Update_Call) Return(_a0 error) *MockBillOwnerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillOwnerRepository_Update_Call) RunAndReturn(run func(context.Context, *customer.Aggregate) error) *MockBillOwnerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillOwnerRepository creates a new instance of MockBillOwnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillOwnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillOwnerRepository {
	mock := &MockBillOwnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
