// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSSENotifier is an autogenerated mock type for the SSENotifier type
type MockSSENotifier struct {
	mock.Mock
}

type MockSSENotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSENotifier) EXPECT() *MockSSENotifier_Expecter {
	return &MockSSENotifier_Expecter{mock: &_m.Mock}
}

// NotifyArea provides a mock function with given fields: ctx, area, eventType, data
func (_m *MockSSENotifier) NotifyArea(ctx context.Context, area string, eventType string, data any) error {
	ret := _m.Called(ctx, area, eventType, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyArea")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = rf(ctx, area, eventType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSSENotifier_NotifyArea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyArea'
type MockSSENotifier_NotifyArea_Call struct {
	*mock.Call
}

// NotifyArea is a helper method to define mock.On call
//   - ctx context.Context
//   - area string
//   - eventType string
//   - data any
func (_e *MockSSENotifier_Expecter) NotifyArea(ctx interface{}, area interface{}, eventType interface{}, data interface{}) *MockSSENotifier_NotifyArea_Call {
	return &MockSSENotifier_NotifyArea_Call{Call: _e.mock.On("NotifyArea", ctx, area, eventType, data)}
}

func (_c *MockSSENotifier_NotifyArea_Call) Run(run func(ctx context.Context, area string, eventType string, data any)) *MockSSENotifier_NotifyArea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(any))
	})
	return _c
}

func (_c *MockSSENotifier_NotifyArea_Call) Return(_a0 error) *MockSSENotifier_NotifyArea_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSENotifier_NotifyArea_Call) RunAndReturn(run func(context.Context, string, string, any) error) *MockSSENotifier_NotifyArea_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSSENotifier creates a new instance of MockSSENotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSENotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSENotifier {
	mock := &MockSSENotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
