// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStockReconciliationRepository is an autogenerated mock type for the StockReconciliationRepository type
type MockStockReconciliationRepository struct {
	mock.Mock
}

type MockStockReconciliationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockReconciliationRepository) EXPECT() *MockStockReconciliationRepository_Expecter {
	return &MockStockReconciliationRepository_Expecter{mock: &_m.Mock}
}

// FindLedgerTotals provides a mock function with given fields: ctx
func (_m *MockStockReconciliationRepository) FindLedgerTotals(ctx context.Context) ([]dto.StockLedgerTotal, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindLedgerTotals")
	}

	var r0 []dto.StockLedgerTotal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.StockLedgerTotal, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.StockLedgerTotal); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.StockLedgerTotal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockReconciliationRepository_FindLedgerTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLedgerTotals'
type MockStockReconciliationRepository_FindLedgerTotals_Call struct {
	*mock.Call
}

// FindLedgerTotals is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStockReconciliationRepository_Expecter) FindLedgerTotals(ctx interface{}) *MockStockReconciliationRepository_FindLedgerTotals_Call {
	return &MockStockReconciliationRepository_FindLedgerTotals_Call{Call: _e.mock.On("FindLedgerTotals", ctx)}
}

func (_c *MockStockReconciliationRepository_FindLedgerTotals_Call) Run(run func(ctx context.Context)) *MockStockReconciliationRepository_FindLedgerTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStockReconciliationRepository_FindLedgerTotals_Call) Return(_a0 []dto.StockLedgerTotal, _a1 error) *MockStockReconciliationRepository_FindLedgerTotals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockReconciliationRepository_FindLedgerTotals_Call) RunAndReturn(run func(context.Context) ([]dto.StockLedgerTotal, error)) *MockStockReconciliationRepository_FindLedgerTotals_Call {
	_c.Call.Return(run)
	return _c
}

// LastEdgeMovementAppliedAt provides a mock function with given fields: ctx
func (_m *MockStockReconciliationRepository) LastEdgeMovementAppliedAt(ctx context.Context) (*time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LastEdgeMovementAppliedAt")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *time.Time); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastEdgeMovementAppliedAt'
type MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call struct {
	*mock.Call
}

// LastEdgeMovementAppliedAt is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStockReconciliationRepository_Expecter) LastEdgeMovementAppliedAt(ctx interface{}) *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call {
	return &MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call{Call: _e.mock.On("LastEdgeMovementAppliedAt", ctx)}
}

func (_c *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call) Run(run func(ctx context.Context)) *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call) Return(_a0 *time.Time, _a1 error) *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call) RunAndReturn(run func(context.Context) (*time.Time, error)) *MockStockReconciliationRepository_LastEdgeMovementAppliedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockReconciliationRepository creates a new instance of MockStockReconciliationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockReconciliationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockReconciliationRepository {
	mock := &MockStockReconciliationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
