// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockProductIngredientRepository is an autogenerated mock type for the ProductIngredientRepository type
type MockProductIngredientRepository struct {
	mock.Mock
}

type MockProductIngredientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductIngredientRepository) EXPECT() *MockProductIngredientRepository_Expecter {
	return &MockProductIngredientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ingredient
func (_m *MockProductIngredientRepository) Create(ctx context.Context, ingredient *dto.ProductIngredient) error {
	ret := _m.Called(ctx, ingredient)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ProductIngredient) error); ok {
		r0 = rf(ctx, ingredient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductIngredientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductIngredientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredient *dto.ProductIngredient
func (_e *MockProductIngredientRepository_Expecter) Create(ctx interface{}, ingredient interface{}) *MockProductIngredientRepository_Create_Call {
	return &MockProductIngredientRepository_Create_Call{Call: _e.mock.On("Create", ctx, ingredient)}
}

func (_c *MockProductIngredientRepository_Create_Call) Run(run func(ctx context.Context, ingredient *dto.ProductIngredient)) *MockProductIngredientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.ProductIngredient))
	})
	return _c
}

func (_c *MockProductIngredientRepository_Create_Call) Return(_a0 error) *MockProductIngredientRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductIngredientRepository_Create_Call) RunAndReturn(run func(context.Context, *dto.ProductIngredient) error) *MockProductIngredientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProductIngredientRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductIngredientRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductIngredientRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductIngredientRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProductIngredientRepository_Delete_Call {
	return &MockProductIngredientRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductIngredientRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProductIngredientRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductIngredientRepository_Delete_Call) Return(_a0 error) *MockProductIngredientRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductIngredientRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockProductIngredientRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCompositeProductID provides a mock function with given fields: ctx, compositeProductID
func (_m *MockProductIngredientRepository) FindByCompositeProductID(ctx context.Context, compositeProductID string) ([]*dto.ProductIngredient, error) {
	ret := _m.Called(ctx, compositeProductID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCompositeProductID")
	}

	var r0 []*dto.ProductIngredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.ProductIngredient, error)); ok {
		return rf(ctx, compositeProductID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.ProductIngredient); ok {
		r0 = rf(ctx, compositeProductID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ProductIngredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, compositeProductID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductIngredientRepository_FindByCompositeProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCompositeProductID'
type MockProductIngredientRepository_FindByCompositeProductID_Call struct {
	*mock.Call
}

// FindByCompositeProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - compositeProductID string
func (_e *MockProductIngredientRepository_Expecter) FindByCompositeProductID(ctx interface{}, compositeProductID interface{}) *MockProductIngredientRepository_FindByCompositeProductID_Call {
	return &MockProductIngredientRepository_FindByCompositeProductID_Call{Call: _e.mock.On("FindByCompositeProductID", ctx, compositeProductID)}
}

func (_c *MockProductIngredientRepository_FindByCompositeProductID_Call) Run(run func(ctx context.Context, compositeProductID string)) *MockProductIngredientRepository_FindByCompositeProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductIngredientRepository_FindByCompositeProductID_Call) Return(_a0 []*dto.ProductIngredient, _a1 error) *MockProductIngredientRepository_FindByCompositeProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductIngredientRepository_FindByCompositeProductID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.ProductIngredient, error)) *MockProductIngredientRepository_FindByCompositeProductID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCompositeProductIDWithProducts provides a mock function with given fields: ctx, compositeProductID
func (_m *MockProductIngredientRepository) FindByCompositeProductIDWithProducts(ctx context.Context, compositeProductID string) ([]*dto.ProductIngredientWithProduct, error) {
	ret := _m.Called(ctx, compositeProductID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCompositeProductIDWithProducts")
	}

	var r0 []*dto.ProductIngredientWithProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.ProductIngredientWithProduct, error)); ok {
		return rf(ctx, compositeProductID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.ProductIngredientWithProduct); ok {
		r0 = rf(ctx, compositeProductID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ProductIngredientWithProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, compositeProductID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCompositeProductIDWithProducts'
type MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call struct {
	*mock.Call
}

// FindByCompositeProductIDWithProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - compositeProductID string
func (_e *MockProductIngredientRepository_Expecter) FindByCompositeProductIDWithProducts(ctx interface{}, compositeProductID interface{}) *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call {
	return &MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call{Call: _e.mock.On("FindByCompositeProductIDWithProducts", ctx, compositeProductID)}
}

func (_c *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call) Run(run func(ctx context.Context, compositeProductID string)) *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call) Return(_a0 []*dto.ProductIngredientWithProduct, _a1 error) *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call) RunAndReturn(run func(context.Context, string) ([]*dto.ProductIngredientWithProduct, error)) *MockProductIngredientRepository_FindByCompositeProductIDWithProducts_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProductIngredientRepository) FindByID(ctx context.Context, id string) (*dto.ProductIngredient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.ProductIngredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ProductIngredient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ProductIngredient); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductIngredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductIngredientRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductIngredientRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductIngredientRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProductIngredientRepository_FindByID_Call {
	return &MockProductIngredientRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductIngredientRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockProductIngredientRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductIngredientRepository_FindByID_Call) Return(_a0 *dto.ProductIngredient, _a1 error) *MockProductIngredientRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductIngredientRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.ProductIngredient, error)) *MockProductIngredientRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIngredientProductID provides a mock function with given fields: ctx, ingredientProductID
func (_m *MockProductIngredientRepository) FindByIngredientProductID(ctx context.Context, ingredientProductID string) ([]*dto.ProductIngredient, error) {
	ret := _m.Called(ctx, ingredientProductID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIngredientProductID")
	}

	var r0 []*dto.ProductIngredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.ProductIngredient, error)); ok {
		return rf(ctx, ingredientProductID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.ProductIngredient); ok {
		r0 = rf(ctx, ingredientProductID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ProductIngredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ingredientProductID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductIngredientRepository_FindByIngredientProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIngredientProductID'
type MockProductIngredientRepository_FindByIngredientProductID_Call struct {
	*mock.Call
}

// FindByIngredientProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientProductID string
func (_e *MockProductIngredientRepository_Expecter) FindByIngredientProductID(ctx interface{}, ingredientProductID interface{}) *MockProductIngredientRepository_FindByIngredientProductID_Call {
	return &MockProductIngredientRepository_FindByIngredientProductID_Call{Call: _e.mock.On("FindByIngredientProductID", ctx, ingredientProductID)}
}

func (_c *MockProductIngredientRepository_FindByIngredientProductID_Call) Run(run func(ctx context.Context, ingredientProductID string)) *MockProductIngredientRepository_FindByIngredientProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductIngredientRepository_FindByIngredientProductID_Call) Return(_a0 []*dto.ProductIngredient, _a1 error) *MockProductIngredientRepository_FindByIngredientProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductIngredientRepository_FindByIngredientProductID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.ProductIngredient, error)) *MockProductIngredientRepository_FindByIngredientProductID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, ingredient
func (_m *MockProductIngredientRepository) Update(ctx context.Context, id string, ingredient *dto.ProductIngredient) error {
	ret := _m.Called(ctx, id, ingredient)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.ProductIngredient) error); ok {
		r0 = rf(ctx, id, ingredient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductIngredientRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductIngredientRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ingredient *dto.ProductIngredient
func (_e *MockProductIngredientRepository_Expecter) Update(ctx interface{}, id interface{}, ingredient interface{}) *MockProductIngredientRepository_Update_Call {
	return &MockProductIngredientRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, ingredient)}
}

func (_c *MockProductIngredientRepository_Update_Call) Run(run func(ctx context.Context, id string, ingredient *dto.ProductIngredient)) *MockProductIngredientRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.ProductIngredient))
	})
	return _c
}

func (_c *MockProductIngredientRepository_Update_Call) Return(_a0 error) *MockProductIngredientRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductIngredientRepository_Update_Call) RunAndReturn(run func(context.Context, string, *dto.ProductIngredient) error) *MockProductIngredientRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductIngredientRepository creates a new instance of MockProductIngredientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductIngredientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductIngredientRepository {
	mock := &MockProductIngredientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
