// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockTelemetryForwarder is an autogenerated mock type for the TelemetryForwarder type
type MockTelemetryForwarder struct {
	mock.Mock
}

type MockTelemetryForwarder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryForwarder) EXPECT() *MockTelemetryForwarder_Expecter {
	return &MockTelemetryForwarder_Expecter{mock: &_m.Mock}
}

// Forward provides a mock function with given fields: ctx, export
func (_m *MockTelemetryForwarder) Forward(ctx context.Context, export dto.TelemetryExport) error {
	ret := _m.Called(ctx, export)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TelemetryExport) error); ok {
		r0 = rf(ctx, export)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTelemetryForwarder_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockTelemetryForwarder_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - export dto.TelemetryExport
func (_e *MockTelemetryForwarder_Expecter) Forward(ctx interface{}, export interface{}) *MockTelemetryForwarder_Forward_Call {
	return &MockTelemetryForwarder_Forward_Call{Call: _e.mock.On("Forward", ctx, export)}
}

func (_c *MockTelemetryForwarder_Forward_Call) Run(run func(ctx context.Context, export dto.TelemetryExport)) *MockTelemetryForwarder_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.TelemetryExport))
	})
	return _c
}

func (_c *MockTelemetryForwarder_Forward_Call) Return(_a0 error) *MockTelemetryForwarder_Forward_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTelemetryForwarder_Forward_Call) RunAndReturn(run func(context.Context, dto.TelemetryExport) error) *MockTelemetryForwarder_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelemetryForwarder creates a new instance of MockTelemetryForwarder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryForwarder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryForwarder {
	mock := &MockTelemetryForwarder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
