// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncReferenceWriter is an autogenerated mock type for the SyncReferenceWriter type
type MockSyncReferenceWriter struct {
	mock.Mock
}

type MockSyncReferenceWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncReferenceWriter) EXPECT() *MockSyncReferenceWriter_Expecter {
	return &MockSyncReferenceWriter_Expecter{mock: &_m.Mock}
}

// UpsertProductResponsibilities provides a mock function with given fields: ctx, responsibilities
func (_m *MockSyncReferenceWriter) UpsertProductResponsibilities(ctx context.Context, responsibilities []dto.ProductResponsibilitySyncPayload) error {
	ret := _m.Called(ctx, responsibilities)

	if len(ret) == 0 {
		panic("no return value specified for UpsertProductResponsibilities")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dto.ProductResponsibilitySyncPayload) error); ok {
		r0 = rf(ctx, responsibilities)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncReferenceWriter_UpsertProductResponsibilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertProductResponsibilities'
type MockSyncReferenceWriter_UpsertProductResponsibilities_Call struct {
	*mock.Call
}

// UpsertProductResponsibilities is a helper method to define mock.On call
//   - ctx context.Context
//   - responsibilities []dto.ProductResponsibilitySyncPayload
func (_e *MockSyncReferenceWriter_Expecter) UpsertProductResponsibilities(ctx interface{}, responsibilities interface{}) *MockSyncReferenceWriter_UpsertProductResponsibilities_Call {
	return &MockSyncReferenceWriter_UpsertProductResponsibilities_Call{Call: _e.mock.On("UpsertProductResponsibilities", ctx, responsibilities)}
}

func (_c *MockSyncReferenceWriter_UpsertProductResponsibilities_Call) Run(run func(ctx context.Context, responsibilities []dto.ProductResponsibilitySyncPayload)) *MockSyncReferenceWriter_UpsertProductResponsibilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dto.ProductResponsibilitySyncPayload))
	})
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertProductResponsibilities_Call) Return(_a0 error) *MockSyncReferenceWriter_UpsertProductResponsibilities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertProductResponsibilities_Call) RunAndReturn(run func(context.Context, []dto.ProductResponsibilitySyncPayload) error) *MockSyncReferenceWriter_UpsertProductResponsibilities_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertProducts provides a mock function with given fields: ctx, products
func (_m *MockSyncReferenceWriter) UpsertProducts(ctx context.Context, products []dto.ProductSyncPayload) error {
	ret := _m.Called(ctx, products)

	if len(ret) == 0 {
		panic("no return value specified for UpsertProducts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dto.ProductSyncPayload) error); ok {
		r0 = rf(ctx, products)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncReferenceWriter_UpsertProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertProducts'
type MockSyncReferenceWriter_UpsertProducts_Call struct {
	*mock.Call
}

// UpsertProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - products []dto.ProductSyncPayload
func (_e *MockSyncReferenceWriter_Expecter) UpsertProducts(ctx interface{}, products interface{}) *MockSyncReferenceWriter_UpsertProducts_Call {
	return &MockSyncReferenceWriter_UpsertProducts_Call{Call: _e.mock.On("UpsertProducts", ctx, products)}
}

func (_c *MockSyncReferenceWriter_UpsertProducts_Call) Run(run func(ctx context.Context, products []dto.ProductSyncPayload)) *MockSyncReferenceWriter_UpsertProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dto.ProductSyncPayload))
	})
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertProducts_Call) Return(_a0 error) *MockSyncReferenceWriter_UpsertProducts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertProducts_Call) RunAndReturn(run func(context.Context, []dto.ProductSyncPayload) error) *MockSyncReferenceWriter_UpsertProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSuppliers provides a mock function with given fields: ctx, suppliers
func (_m *MockSyncReferenceWriter) UpsertSuppliers(ctx context.Context, suppliers []dto.SupplierSyncPayload) error {
	ret := _m.Called(ctx, suppliers)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSuppliers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dto.SupplierSyncPayload) error); ok {
		r0 = rf(ctx, suppliers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncReferenceWriter_UpsertSuppliers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSuppliers'
type MockSyncReferenceWriter_UpsertSuppliers_Call struct {
	*mock.Call
}

// UpsertSuppliers is a helper method to define mock.On call
//   - ctx context.Context
//   - suppliers []dto.SupplierSyncPayload
func (_e *MockSyncReferenceWriter_Expecter) UpsertSuppliers(ctx interface{}, suppliers interface{}) *MockSyncReferenceWriter_UpsertSuppliers_Call {
	return &MockSyncReferenceWriter_UpsertSuppliers_Call{Call: _e.mock.On("UpsertSuppliers", ctx, suppliers)}
}

func (_c *MockSyncReferenceWriter_UpsertSuppliers_Call) Run(run func(ctx context.Context, suppliers []dto.SupplierSyncPayload)) *MockSyncReferenceWriter_UpsertSuppliers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dto.SupplierSyncPayload))
	})
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertSuppliers_Call) Return(_a0 error) *MockSyncReferenceWriter_UpsertSuppliers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertSuppliers_Call) RunAndReturn(run func(context.Context, []dto.SupplierSyncPayload) error) *MockSyncReferenceWriter_UpsertSuppliers_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUsers provides a mock function with given fields: ctx, users
func (_m *MockSyncReferenceWriter) UpsertUsers(ctx context.Context, users []dto.UserSyncPayload) error {
	ret := _m.Called(ctx, users)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dto.UserSyncPayload) error); ok {
		r0 = rf(ctx, users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncReferenceWriter_UpsertUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUsers'
type MockSyncReferenceWriter_UpsertUsers_Call struct {
	*mock.Call
}

// UpsertUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - users []dto.UserSyncPayload
func (_e *MockSyncReferenceWriter_Expecter) UpsertUsers(ctx interface{}, users interface{}) *MockSyncReferenceWriter_UpsertUsers_Call {
	return &MockSyncReferenceWriter_UpsertUsers_Call{Call: _e.mock.On("UpsertUsers", ctx, users)}
}

func (_c *MockSyncReferenceWriter_UpsertUsers_Call) Run(run func(ctx context.Context, users []dto.UserSyncPayload)) *MockSyncReferenceWriter_UpsertUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dto.UserSyncPayload))
	})
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertUsers_Call) Return(_a0 error) *MockSyncReferenceWriter_UpsertUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncReferenceWriter_UpsertUsers_Call) RunAndReturn(run func(context.Context, []dto.UserSyncPayload) error) *MockSyncReferenceWriter_UpsertUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncReferenceWriter creates a new instance of MockSyncReferenceWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncReferenceWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncReferenceWriter {
	mock := &MockSyncReferenceWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
