// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncPushClient is an autogenerated mock type for the SyncPushClient type
type MockSyncPushClient struct {
	mock.Mock
}

type MockSyncPushClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncPushClient) EXPECT() *MockSyncPushClient_Expecter {
	return &MockSyncPushClient_Expecter{mock: &_m.Mock}
}

// Push provides a mock function with given fields: ctx, req
func (_m *MockSyncPushClient) Push(ctx context.Context, req *dto.SyncPushRequest) (*dto.SyncPushResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 *dto.SyncPushResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SyncPushRequest) (*dto.SyncPushResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SyncPushRequest) *dto.SyncPushResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SyncPushResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SyncPushRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncPushClient_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockSyncPushClient_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.SyncPushRequest
func (_e *MockSyncPushClient_Expecter) Push(ctx interface{}, req interface{}) *MockSyncPushClient_Push_Call {
	return &MockSyncPushClient_Push_Call{Call: _e.mock.On("Push", ctx, req)}
}

func (_c *MockSyncPushClient_Push_Call) Run(run func(ctx context.Context, req *dto.SyncPushRequest)) *MockSyncPushClient_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SyncPushRequest))
	})
	return _c
}

func (_c *MockSyncPushClient_Push_Call) Return(_a0 *dto.SyncPushResponse, _a1 error) *MockSyncPushClient_Push_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncPushClient_Push_Call) RunAndReturn(run func(context.Context, *dto.SyncPushRequest) (*dto.SyncPushResponse, error)) *MockSyncPushClient_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncPushClient creates a new instance of MockSyncPushClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncPushClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncPushClient {
	mock := &MockSyncPushClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
