// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	support_document "laguna-escondida/backend/internal/domain/aggregate/support_document"
)

// MockSupportDocumentRepository is an autogenerated mock type for the SupportDocumentRepository type
type MockSupportDocumentRepository struct {
	mock.Mock
}

type MockSupportDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupportDocumentRepository) EXPECT() *MockSupportDocumentRepository_Expecter {
	return &MockSupportDocumentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, doc
func (_m *MockSupportDocumentRepository) Create(ctx context.Context, doc *support_document.Aggregate) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *support_document.Aggregate) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportDocumentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSupportDocumentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *support_document.Aggregate
func (_e *MockSupportDocumentRepository_Expecter) Create(ctx interface{}, doc interface{}) *MockSupportDocumentRepository_Create_Call {
	return &MockSupportDocumentRepository_Create_Call{Call: _e.mock.On("Create", ctx, doc)}
}

func (_c *MockSupportDocumentRepository_Create_Call) Run(run func(ctx context.Context, doc *support_document.Aggregate)) *MockSupportDocumentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*support_document.Aggregate))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_Create_Call) Return(_a0 error) *MockSupportDocumentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportDocumentRepository_Create_Call) RunAndReturn(run func(context.Context, *support_document.Aggregate) error) *MockSupportDocumentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockSupportDocumentRepository) FindAllByCriteria(ctx context.Context, criteria *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCriteria")
	}

	var r0 []dto.SupportDocumentListItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SupportDocumentCriteria) []dto.SupportDocumentListItem); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SupportDocumentListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SupportDocumentCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportDocumentRepository_FindAllByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByCriteria'
type MockSupportDocumentRepository_FindAllByCriteria_Call struct {
	*mock.Call
}

// FindAllByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.SupportDocumentCriteria
func (_e *MockSupportDocumentRepository_Expecter) FindAllByCriteria(ctx interface{}, criteria interface{}) *MockSupportDocumentRepository_FindAllByCriteria_Call {
	return &MockSupportDocumentRepository_FindAllByCriteria_Call{Call: _e.mock.On("FindAllByCriteria", ctx, criteria)}
}

func (_c *MockSupportDocumentRepository_FindAllByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.SupportDocumentCriteria)) *MockSupportDocumentRepository_FindAllByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SupportDocumentCriteria))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_FindAllByCriteria_Call) Return(_a0 []dto.SupportDocumentListItem, _a1 error) *MockSupportDocumentRepository_FindAllByCriteria_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportDocumentRepository_FindAllByCriteria_Call) RunAndReturn(run func(context.Context, *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, error)) *MockSupportDocumentRepository_FindAllByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockSupportDocumentRepository) FindByCriteria(ctx context.Context, criteria *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, int64, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []dto.SupportDocumentListItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, int64, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SupportDocumentCriteria) []dto.SupportDocumentListItem); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SupportDocumentListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SupportDocumentCriteria) int64); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.SupportDocumentCriteria) error); ok {
		r2 = rf(ctx, criteria)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSupportDocumentRepository_FindByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCriteria'
type MockSupportDocumentRepository_FindByCriteria_Call struct {
	*mock.Call
}

// FindByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.SupportDocumentCriteria
func (_e *MockSupportDocumentRepository_Expecter) FindByCriteria(ctx interface{}, criteria interface{}) *MockSupportDocumentRepository_FindByCriteria_Call {
	return &MockSupportDocumentRepository_FindByCriteria_Call{Call: _e.mock.On("FindByCriteria", ctx, criteria)}
}

func (_c *MockSupportDocumentRepository_FindByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.SupportDocumentCriteria)) *MockSupportDocumentRepository_FindByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SupportDocumentCriteria))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_FindByCriteria_Call) Return(_a0 []dto.SupportDocumentListItem, _a1 int64, _a2 error) *MockSupportDocumentRepository_FindByCriteria_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSupportDocumentRepository_FindByCriteria_Call) RunAndReturn(run func(context.Context, *dto.SupportDocumentCriteria) ([]dto.SupportDocumentListItem, int64, error)) *MockSupportDocumentRepository_FindByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNullDocumentURL provides a mock function with given fields: ctx
func (_m *MockSupportDocumentRepository) FindByNullDocumentURL(ctx context.Context) ([]*dto.SupportDocumentWithTascode, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindByNullDocumentURL")
	}

	var r0 []*dto.SupportDocumentWithTascode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.SupportDocumentWithTascode, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.SupportDocumentWithTascode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.SupportDocumentWithTascode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportDocumentRepository_FindByNullDocumentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNullDocumentURL'
type MockSupportDocumentRepository_FindByNullDocumentURL_Call struct {
	*mock.Call
}

// FindByNullDocumentURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSupportDocumentRepository_Expecter) FindByNullDocumentURL(ctx interface{}) *MockSupportDocumentRepository_FindByNullDocumentURL_Call {
	return &MockSupportDocumentRepository_FindByNullDocumentURL_Call{Call: _e.mock.On("FindByNullDocumentURL", ctx)}
}

func (_c *MockSupportDocumentRepository_FindByNullDocumentURL_Call) Run(run func(ctx context.Context)) *MockSupportDocumentRepository_FindByNullDocumentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_FindByNullDocumentURL_Call) Return(_a0 []*dto.SupportDocumentWithTascode, _a1 error) *MockSupportDocumentRepository_FindByNullDocumentURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportDocumentRepository_FindByNullDocumentURL_Call) RunAndReturn(run func(context.Context) ([]*dto.SupportDocumentWithTascode, error)) *MockSupportDocumentRepository_FindByNullDocumentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDocumentURL provides a mock function with given fields: ctx, docID, documentURL
func (_m *MockSupportDocumentRepository) UpdateDocumentURL(ctx context.Context, docID string, documentURL string) error {
	ret := _m.Called(ctx, docID, documentURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, docID, documentURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportDocumentRepository_UpdateDocumentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDocumentURL'
type MockSupportDocumentRepository_UpdateDocumentURL_Call struct {
	*mock.Call
}

// UpdateDocumentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - documentURL string
func (_e *MockSupportDocumentRepository_Expecter) UpdateDocumentURL(ctx interface{}, docID interface{}, documentURL interface{}) *MockSupportDocumentRepository_UpdateDocumentURL_Call {
	return &MockSupportDocumentRepository_UpdateDocumentURL_Call{Call: _e.mock.On("UpdateDocumentURL", ctx, docID, documentURL)}
}

func (_c *MockSupportDocumentRepository_UpdateDocumentURL_Call) Run(run func(ctx context.Context, docID string, documentURL string)) *MockSupportDocumentRepository_UpdateDocumentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_UpdateDocumentURL_Call) Return(_a0 error) *MockSupportDocumentRepository_UpdateDocumentURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportDocumentRepository_UpdateDocumentURL_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSupportDocumentRepository_UpdateDocumentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStoragePaths provides a mock function with given fields: ctx, docID, pdfPath, xmlPath
func (_m *MockSupportDocumentRepository) UpdateStoragePaths(ctx context.Context, docID string, pdfPath *string, xmlPath *string) error {
	ret := _m.Called(ctx, docID, pdfPath, xmlPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStoragePaths")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) error); ok {
		r0 = rf(ctx, docID, pdfPath, xmlPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportDocumentRepository_UpdateStoragePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStoragePaths'
type MockSupportDocumentRepository_UpdateStoragePaths_Call struct {
	*mock.Call
}

// UpdateStoragePaths is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - pdfPath *string
//   - xmlPath *string
func (_e *MockSupportDocumentRepository_Expecter) UpdateStoragePaths(ctx interface{}, docID interface{}, pdfPath interface{}, xmlPath interface{}) *MockSupportDocumentRepository_UpdateStoragePaths_Call {
	return &MockSupportDocumentRepository_UpdateStoragePaths_Call{Call: _e.mock.On("UpdateStoragePaths", ctx, docID, pdfPath, xmlPath)}
}

func (_c *MockSupportDocumentRepository_UpdateStoragePaths_Call) Run(run func(ctx context.Context, docID string, pdfPath *string, xmlPath *string)) *MockSupportDocumentRepository_UpdateStoragePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockSupportDocumentRepository_UpdateStoragePaths_Call) Return(_a0 error) *MockSupportDocumentRepository_UpdateStoragePaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportDocumentRepository_UpdateStoragePaths_Call) RunAndReturn(run func(context.Context, string, *string, *string) error) *MockSupportDocumentRepository_UpdateStoragePaths_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupportDocumentRepository creates a new instance of MockSupportDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupportDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupportDocumentRepository {
	mock := &MockSupportDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
