// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	purchase_entry "laguna-escondida/backend/internal/domain/aggregate/purchase_entry"

	time "time"
)

// MockPurchaseEntryRepository is an autogenerated mock type for the PurchaseEntryRepository type
type MockPurchaseEntryRepository struct {
	mock.Mock
}

type MockPurchaseEntryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseEntryRepository) EXPECT() *MockPurchaseEntryRepository_Expecter {
	return &MockPurchaseEntryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entry
func (_m *MockPurchaseEntryRepository) Create(ctx context.Context, entry *purchase_entry.Aggregate) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *purchase_entry.Aggregate) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseEntryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPurchaseEntryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *purchase_entry.Aggregate
func (_e *MockPurchaseEntryRepository_Expecter) Create(ctx interface{}, entry interface{}) *MockPurchaseEntryRepository_Create_Call {
	return &MockPurchaseEntryRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *MockPurchaseEntryRepository_Create_Call) Run(run func(ctx context.Context, entry *purchase_entry.Aggregate)) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*purchase_entry.Aggregate))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_Create_Call) Return(_a0 error) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseEntryRepository_Create_Call) RunAndReturn(run func(context.Context, *purchase_entry.Aggregate) error) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockPurchaseEntryRepository) FindAll(ctx context.Context) ([]*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPurchaseEntryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPurchaseEntryRepository_Expecter) FindAll(ctx interface{}) *MockPurchaseEntryRepository_FindAll_Call {
	return &MockPurchaseEntryRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) Return(_a0 []*dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCriteria provides a mock function with given fields: ctx, criteria
func (_m *MockPurchaseEntryRepository) FindByCriteria(ctx context.Context, criteria *dto.PurchaseEntryListCriteria) ([]*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []*dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.PurchaseEntryListCriteria) ([]*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.PurchaseEntryListCriteria) []*dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.PurchaseEntryListCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCriteria'
type MockPurchaseEntryRepository_FindByCriteria_Call struct {
	*mock.Call
}

// FindByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *dto.PurchaseEntryListCriteria
func (_e *MockPurchaseEntryRepository_Expecter) FindByCriteria(ctx interface{}, criteria interface{}) *MockPurchaseEntryRepository_FindByCriteria_Call {
	return &MockPurchaseEntryRepository_FindByCriteria_Call{Call: _e.mock.On("FindByCriteria", ctx, criteria)}
}

func (_c *MockPurchaseEntryRepository_FindByCriteria_Call) Run(run func(ctx context.Context, criteria *dto.PurchaseEntryListCriteria)) *MockPurchaseEntryRepository_FindByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.PurchaseEntryListCriteria))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByCriteria_Call) Return(_a0 []*dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindByCriteria_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByCriteria_Call) RunAndReturn(run func(context.Context, *dto.PurchaseEntryListCriteria) ([]*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPurchaseEntryRepository) FindByID(ctx context.Context, id string) (*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPurchaseEntryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPurchaseEntryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPurchaseEntryRepository_FindByID_Call {
	return &MockPurchaseEntryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) Return(_a0 *dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockPurchaseEntryRepository) FindBySupplierID(ctx context.Context, supplierID string) ([]*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 []*dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockPurchaseEntryRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID string
func (_e *MockPurchaseEntryRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	return &MockPurchaseEntryRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID string)) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) Return(_a0 []*dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPurchaseSummary provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockPurchaseEntryRepository) GetPurchaseSummary(ctx context.Context, startDate time.Time, endDate time.Time) (*dto.PurchaseSummary, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPurchaseSummary")
	}

	var r0 *dto.PurchaseSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*dto.PurchaseSummary, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *dto.PurchaseSummary); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PurchaseSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_GetPurchaseSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPurchaseSummary'
type MockPurchaseEntryRepository_GetPurchaseSummary_Call struct {
	*mock.Call
}

// GetPurchaseSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPurchaseEntryRepository_Expecter) GetPurchaseSummary(ctx interface{}, startDate interface{}, endDate interface{}) *MockPurchaseEntryRepository_GetPurchaseSummary_Call {
	return &MockPurchaseEntryRepository_GetPurchaseSummary_Call{Call: _e.mock.On("GetPurchaseSummary", ctx, startDate, endDate)}
}

func (_c *MockPurchaseEntryRepository_GetPurchaseSummary_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time)) *MockPurchaseEntryRepository_GetPurchaseSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_GetPurchaseSummary_Call) Return(_a0 *dto.PurchaseSummary, _a1 error) *MockPurchaseEntryRepository_GetPurchaseSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_GetPurchaseSummary_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (*dto.PurchaseSummary, error)) *MockPurchaseEntryRepository_GetPurchaseSummary_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStoragePaths provides a mock function with given fields: ctx, id, pdfPath, xmlPath
func (_m *MockPurchaseEntryRepository) UpdateStoragePaths(ctx context.Context, id string, pdfPath *string, xmlPath *string) error {
	ret := _m.Called(ctx, id, pdfPath, xmlPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStoragePaths")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) error); ok {
		r0 = rf(ctx, id, pdfPath, xmlPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseEntryRepository_UpdateStoragePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStoragePaths'
type MockPurchaseEntryRepository_UpdateStoragePaths_Call struct {
	*mock.Call
}

// UpdateStoragePaths is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - pdfPath *string
//   - xmlPath *string
func (_e *MockPurchaseEntryRepository_Expecter) UpdateStoragePaths(ctx interface{}, id interface{}, pdfPath interface{}, xmlPath interface{}) *MockPurchaseEntryRepository_UpdateStoragePaths_Call {
	return &MockPurchaseEntryRepository_UpdateStoragePaths_Call{Call: _e.mock.On("UpdateStoragePaths", ctx, id, pdfPath, xmlPath)}
}

func (_c *MockPurchaseEntryRepository_UpdateStoragePaths_Call) Run(run func(ctx context.Context, id string, pdfPath *string, xmlPath *string)) *MockPurchaseEntryRepository_UpdateStoragePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_UpdateStoragePaths_Call) Return(_a0 error) *MockPurchaseEntryRepository_UpdateStoragePaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseEntryRepository_UpdateStoragePaths_Call) RunAndReturn(run func(context.Context, string, *string, *string) error) *MockPurchaseEntryRepository_UpdateStoragePaths_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPurchaseEntryRepository creates a new instance of MockPurchaseEntryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseEntryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseEntryRepository {
	mock := &MockPurchaseEntryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
