// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOpenBillProductSSENotifier is an autogenerated mock type for the OpenBillProductSSENotifier type
type MockOpenBillProductSSENotifier struct {
	mock.Mock
}

type MockOpenBillProductSSENotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenBillProductSSENotifier) EXPECT() *MockOpenBillProductSSENotifier_Expecter {
	return &MockOpenBillProductSSENotifier_Expecter{mock: &_m.Mock}
}

// NotifyArea provides a mock function with given fields: ctx, area, eventType, data
func (_m *MockOpenBillProductSSENotifier) NotifyArea(ctx context.Context, area string, eventType string, data *dto.OpenBillProductSSE) error {
	ret := _m.Called(ctx, area, eventType, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyArea")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.OpenBillProductSSE) error); ok {
		r0 = rf(ctx, area, eventType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOpenBillProductSSENotifier_NotifyArea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyArea'
type MockOpenBillProductSSENotifier_NotifyArea_Call struct {
	*mock.Call
}

// NotifyArea is a helper method to define mock.On call
//   - ctx context.Context
//   - area string
//   - eventType string
//   - data *dto.OpenBillProductSSE
func (_e *MockOpenBillProductSSENotifier_Expecter) NotifyArea(ctx interface{}, area interface{}, eventType interface{}, data interface{}) *MockOpenBillProductSSENotifier_NotifyArea_Call {
	return &MockOpenBillProductSSENotifier_NotifyArea_Call{Call: _e.mock.On("NotifyArea", ctx, area, eventType, data)}
}

func (_c *MockOpenBillProductSSENotifier_NotifyArea_Call) Run(run func(ctx context.Context, area string, eventType string, data *dto.OpenBillProductSSE)) *MockOpenBillProductSSENotifier_NotifyArea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dto.OpenBillProductSSE))
	})
	return _c
}

func (_c *MockOpenBillProductSSENotifier_NotifyArea_Call) Return(_a0 error) *MockOpenBillProductSSENotifier_NotifyArea_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOpenBillProductSSENotifier_NotifyArea_Call) RunAndReturn(run func(context.Context, string, string, *dto.OpenBillProductSSE) error) *MockOpenBillProductSSENotifier_NotifyArea_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOpenBillProductSSENotifier creates a new instance of MockOpenBillProductSSENotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenBillProductSSENotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenBillProductSSENotifier {
	mock := &MockOpenBillProductSSENotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
