// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSyncReferenceReader is an autogenerated mock type for the SyncReferenceReader type
type MockSyncReferenceReader struct {
	mock.Mock
}

type MockSyncReferenceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncReferenceReader) EXPECT() *MockSyncReferenceReader_Expecter {
	return &MockSyncReferenceReader_Expecter{mock: &_m.Mock}
}

// FindChangedProducts provides a mock function with given fields: ctx, since
func (_m *MockSyncReferenceReader) FindChangedProducts(ctx context.Context, since time.Time) ([]dto.ProductSyncPayload, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for FindChangedProducts")
	}

	var r0 []dto.ProductSyncPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]dto.ProductSyncPayload, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []dto.ProductSyncPayload); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProductSyncPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncReferenceReader_FindChangedProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindChangedProducts'
type MockSyncReferenceReader_FindChangedProducts_Call struct {
	*mock.Call
}

// FindChangedProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSyncReferenceReader_Expecter) FindChangedProducts(ctx interface{}, since interface{}) *MockSyncReferenceReader_FindChangedProducts_Call {
	return &MockSyncReferenceReader_FindChangedProducts_Call{Call: _e.mock.On("FindChangedProducts", ctx, since)}
}

func (_c *MockSyncReferenceReader_FindChangedProducts_Call) Run(run func(ctx context.Context, since time.Time)) *MockSyncReferenceReader_FindChangedProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedProducts_Call) Return(_a0 []dto.ProductSyncPayload, _a1 error) *MockSyncReferenceReader_FindChangedProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedProducts_Call) RunAndReturn(run func(context.Context, time.Time) ([]dto.ProductSyncPayload, error)) *MockSyncReferenceReader_FindChangedProducts_Call {
	_c.Call.Return(run)
	return _c
}

// FindChangedSuppliers provides a mock function with given fields: ctx, since
func (_m *MockSyncReferenceReader) FindChangedSuppliers(ctx context.Context, since time.Time) ([]dto.SupplierSyncPayload, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for FindChangedSuppliers")
	}

	var r0 []dto.SupplierSyncPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]dto.SupplierSyncPayload, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []dto.SupplierSyncPayload); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SupplierSyncPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncReferenceReader_FindChangedSuppliers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindChangedSuppliers'
type MockSyncReferenceReader_FindChangedSuppliers_Call struct {
	*mock.Call
}

// FindChangedSuppliers is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSyncReferenceReader_Expecter) FindChangedSuppliers(ctx interface{}, since interface{}) *MockSyncReferenceReader_FindChangedSuppliers_Call {
	return &MockSyncReferenceReader_FindChangedSuppliers_Call{Call: _e.mock.On("FindChangedSuppliers", ctx, since)}
}

func (_c *MockSyncReferenceReader_FindChangedSuppliers_Call) Run(run func(ctx context.Context, since time.Time)) *MockSyncReferenceReader_FindChangedSuppliers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedSuppliers_Call) Return(_a0 []dto.SupplierSyncPayload, _a1 error) *MockSyncReferenceReader_FindChangedSuppliers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedSuppliers_Call) RunAndReturn(run func(context.Context, time.Time) ([]dto.SupplierSyncPayload, error)) *MockSyncReferenceReader_FindChangedSuppliers_Call {
	_c.Call.Return(run)
	return _c
}

// FindChangedUsers provides a mock function with given fields: ctx, since
func (_m *MockSyncReferenceReader) FindChangedUsers(ctx context.Context, since time.Time) ([]dto.UserSyncPayload, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for FindChangedUsers")
	}

	var r0 []dto.UserSyncPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]dto.UserSyncPayload, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []dto.UserSyncPayload); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserSyncPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncReferenceReader_FindChangedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindChangedUsers'
type MockSyncReferenceReader_FindChangedUsers_Call struct {
	*mock.Call
}

// FindChangedUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSyncReferenceReader_Expecter) FindChangedUsers(ctx interface{}, since interface{}) *MockSyncReferenceReader_FindChangedUsers_Call {
	return &MockSyncReferenceReader_FindChangedUsers_Call{Call: _e.mock.On("FindChangedUsers", ctx, since)}
}

func (_c *MockSyncReferenceReader_FindChangedUsers_Call) Run(run func(ctx context.Context, since time.Time)) *MockSyncReferenceReader_FindChangedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedUsers_Call) Return(_a0 []dto.UserSyncPayload, _a1 error) *MockSyncReferenceReader_FindChangedUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncReferenceReader_FindChangedUsers_Call) RunAndReturn(run func(context.Context, time.Time) ([]dto.UserSyncPayload, error)) *MockSyncReferenceReader_FindChangedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncReferenceReader creates a new instance of MockSyncReferenceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncReferenceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncReferenceReader {
	mock := &MockSyncReferenceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
