// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	command "laguna-escondida/backend/internal/domain/aggregate/command"

	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandRepository is an autogenerated mock type for the CommandRepository type
type MockCommandRepository struct {
	mock.Mock
}

type MockCommandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRepository) EXPECT() *MockCommandRepository_Expecter {
	return &MockCommandRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *MockCommandRepository) Create(ctx context.Context, cmd *command.Aggregate) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *command.Aggregate) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommandRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *command.Aggregate
func (_e *MockCommandRepository_Expecter) Create(ctx interface{}, cmd interface{}) *MockCommandRepository_Create_Call {
	return &MockCommandRepository_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *MockCommandRepository_Create_Call) Run(run func(ctx context.Context, cmd *command.Aggregate)) *MockCommandRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*command.Aggregate))
	})
	return _c
}

func (_c *MockCommandRepository_Create_Call) Return(_a0 error) *MockCommandRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandRepository_Create_Call) RunAndReturn(run func(context.Context, *command.Aggregate) error) *MockCommandRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByArea provides a mock function with given fields: ctx, area
func (_m *MockCommandRepository) FindByArea(ctx context.Context, area string) ([]*dto.Command, error) {
	ret := _m.Called(ctx, area)

	if len(ret) == 0 {
		panic("no return value specified for FindByArea")
	}

	var r0 []*dto.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.Command, error)); ok {
		return rf(ctx, area)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.Command); ok {
		r0 = rf(ctx, area)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, area)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRepository_FindByArea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByArea'
type MockCommandRepository_FindByArea_Call struct {
	*mock.Call
}

// FindByArea is a helper method to define mock.On call
//   - ctx context.Context
//   - area string
func (_e *MockCommandRepository_Expecter) FindByArea(ctx interface{}, area interface{}) *MockCommandRepository_FindByArea_Call {
	return &MockCommandRepository_FindByArea_Call{Call: _e.mock.On("FindByArea", ctx, area)}
}

func (_c *MockCommandRepository_FindByArea_Call) Run(run func(ctx context.Context, area string)) *MockCommandRepository_FindByArea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandRepository_FindByArea_Call) Return(_a0 []*dto.Command, _a1 error) *MockCommandRepository_FindByArea_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRepository_FindByArea_Call) RunAndReturn(run func(context.Context, string) ([]*dto.Command, error)) *MockCommandRepository_FindByArea_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCommandRepository) FindByID(ctx context.Context, id string) (*command.Aggregate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *command.Aggregate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*command.Aggregate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *command.Aggregate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.Aggregate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCommandRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommandRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCommandRepository_FindByID_Call {
	return &MockCommandRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCommandRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCommandRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandRepository_FindByID_Call) Return(_a0 *command.Aggregate, _a1 error) *MockCommandRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*command.Aggregate, error)) *MockCommandRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingByArea provides a mock function with given fields: ctx, area
func (_m *MockCommandRepository) FindPendingByArea(ctx context.Context, area string) ([]*dto.Command, error) {
	ret := _m.Called(ctx, area)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingByArea")
	}

	var r0 []*dto.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.Command, error)); ok {
		return rf(ctx, area)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.Command); ok {
		r0 = rf(ctx, area)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, area)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRepository_FindPendingByArea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingByArea'
type MockCommandRepository_FindPendingByArea_Call struct {
	*mock.Call
}

// FindPendingByArea is a helper method to define mock.On call
//   - ctx context.Context
//   - area string
func (_e *MockCommandRepository_Expecter) FindPendingByArea(ctx interface{}, area interface{}) *MockCommandRepository_FindPendingByArea_Call {
	return &MockCommandRepository_FindPendingByArea_Call{Call: _e.mock.On("FindPendingByArea", ctx, area)}
}

func (_c *MockCommandRepository_FindPendingByArea_Call) Run(run func(ctx context.Context, area string)) *MockCommandRepository_FindPendingByArea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommandRepository_FindPendingByArea_Call) Return(_a0 []*dto.Command, _a1 error) *MockCommandRepository_FindPendingByArea_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRepository_FindPendingByArea_Call) RunAndReturn(run func(context.Context, string) ([]*dto.Command, error)) *MockCommandRepository_FindPendingByArea_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductPreparationResponsibilities provides a mock function with given fields: ctx, productIDs
func (_m *MockCommandRepository) GetProductPreparationResponsibilities(ctx context.Context, productIDs []string) ([]dto.ProductPreparationResponsibilityWithProduct, error) {
	ret := _m.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetProductPreparationResponsibilities")
	}

	var r0 []dto.ProductPreparationResponsibilityWithProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]dto.ProductPreparationResponsibilityWithProduct, error)); ok {
		return rf(ctx, productIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []dto.ProductPreparationResponsibilityWithProduct); ok {
		r0 = rf(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProductPreparationResponsibilityWithProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRepository_GetProductPreparationResponsibilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductPreparationResponsibilities'
type MockCommandRepository_GetProductPreparationResponsibilities_Call struct {
	*mock.Call
}

// GetProductPreparationResponsibilities is a helper method to define mock.On call
//   - ctx context.Context
//   - productIDs []string
func (_e *MockCommandRepository_Expecter) GetProductPreparationResponsibilities(ctx interface{}, productIDs interface{}) *MockCommandRepository_GetProductPreparationResponsibilities_Call {
	return &MockCommandRepository_GetProductPreparationResponsibilities_Call{Call: _e.mock.On("GetProductPreparationResponsibilities", ctx, productIDs)}
}

func (_c *MockCommandRepository_GetProductPreparationResponsibilities_Call) Run(run func(ctx context.Context, productIDs []string)) *MockCommandRepository_GetProductPreparationResponsibilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCommandRepository_GetProductPreparationResponsibilities_Call) Return(_a0 []dto.ProductPreparationResponsibilityWithProduct, _a1 error) *MockCommandRepository_GetProductPreparationResponsibilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRepository_GetProductPreparationResponsibilities_Call) RunAndReturn(run func(context.Context, []string) ([]dto.ProductPreparationResponsibilityWithProduct, error)) *MockCommandRepository_GetProductPreparationResponsibilities_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, cmd
func (_m *MockCommandRepository) Update(ctx context.Context, cmd *command.Aggregate) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *command.Aggregate) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCommandRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *command.Aggregate
func (_e *MockCommandRepository_Expecter) Update(ctx interface{}, cmd interface{}) *MockCommandRepository_Update_Call {
	return &MockCommandRepository_Update_Call{Call: _e.mock.On("Update", ctx, cmd)}
}

func (_c *MockCommandRepository_Update_Call) Run(run func(ctx context.Context, cmd *command.Aggregate)) *MockCommandRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*command.Aggregate))
	})
	return _c
}

func (_c *MockCommandRepository_Update_Call) Return(_a0 error) *MockCommandRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandRepository_Update_Call) RunAndReturn(run func(context.Context, *command.Aggregate) error) *MockCommandRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandRepository creates a new instance of MockCommandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRepository {
	mock := &MockCommandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
