// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockSupplierCatalogRepository is an autogenerated mock type for the SupplierCatalogRepository type
type MockSupplierCatalogRepository struct {
	mock.Mock
}

type MockSupplierCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierCatalogRepository) EXPECT() *MockSupplierCatalogRepository_Expecter {
	return &MockSupplierCatalogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, catalog
func (_m *MockSupplierCatalogRepository) Create(ctx context.Context, catalog *dto.SupplierCatalog) error {
	ret := _m.Called(ctx, catalog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SupplierCatalog) error); ok {
		r0 = rf(ctx, catalog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierCatalogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSupplierCatalogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - catalog *dto.SupplierCatalog
func (_e *MockSupplierCatalogRepository_Expecter) Create(ctx interface{}, catalog interface{}) *MockSupplierCatalogRepository_Create_Call {
	return &MockSupplierCatalogRepository_Create_Call{Call: _e.mock.On("Create", ctx, catalog)}
}

func (_c *MockSupplierCatalogRepository_Create_Call) Run(run func(ctx context.Context, catalog *dto.SupplierCatalog)) *MockSupplierCatalogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SupplierCatalog))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_Create_Call) Return(_a0 error) *MockSupplierCatalogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierCatalogRepository_Create_Call) RunAndReturn(run func(context.Context, *dto.SupplierCatalog) error) *MockSupplierCatalogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSupplierCatalogRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierCatalogRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSupplierCatalogRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSupplierCatalogRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSupplierCatalogRepository_Delete_Call {
	return &MockSupplierCatalogRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSupplierCatalogRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSupplierCatalogRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_Delete_Call) Return(_a0 error) *MockSupplierCatalogRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierCatalogRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSupplierCatalogRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSupplierCatalogRepository) FindByID(ctx context.Context, id string) (*dto.SupplierCatalog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.SupplierCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.SupplierCatalog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.SupplierCatalog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SupplierCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierCatalogRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSupplierCatalogRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSupplierCatalogRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSupplierCatalogRepository_FindByID_Call {
	return &MockSupplierCatalogRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSupplierCatalogRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockSupplierCatalogRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_FindByID_Call) Return(_a0 *dto.SupplierCatalog, _a1 error) *MockSupplierCatalogRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierCatalogRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.SupplierCatalog, error)) *MockSupplierCatalogRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProductID provides a mock function with given fields: ctx, productID
func (_m *MockSupplierCatalogRepository) FindByProductID(ctx context.Context, productID string) ([]*dto.SupplierCatalogWithSupplier, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProductID")
	}

	var r0 []*dto.SupplierCatalogWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.SupplierCatalogWithSupplier, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.SupplierCatalogWithSupplier); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.SupplierCatalogWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierCatalogRepository_FindByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProductID'
type MockSupplierCatalogRepository_FindByProductID_Call struct {
	*mock.Call
}

// FindByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockSupplierCatalogRepository_Expecter) FindByProductID(ctx interface{}, productID interface{}) *MockSupplierCatalogRepository_FindByProductID_Call {
	return &MockSupplierCatalogRepository_FindByProductID_Call{Call: _e.mock.On("FindByProductID", ctx, productID)}
}

func (_c *MockSupplierCatalogRepository_FindByProductID_Call) Run(run func(ctx context.Context, productID string)) *MockSupplierCatalogRepository_FindByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_FindByProductID_Call) Return(_a0 []*dto.SupplierCatalogWithSupplier, _a1 error) *MockSupplierCatalogRepository_FindByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierCatalogRepository_FindByProductID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.SupplierCatalogWithSupplier, error)) *MockSupplierCatalogRepository_FindByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierAndProduct provides a mock function with given fields: ctx, supplierID, productID
func (_m *MockSupplierCatalogRepository) FindBySupplierAndProduct(ctx context.Context, supplierID string, productID string) (*dto.SupplierCatalog, error) {
	ret := _m.Called(ctx, supplierID, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierAndProduct")
	}

	var r0 *dto.SupplierCatalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.SupplierCatalog, error)); ok {
		return rf(ctx, supplierID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.SupplierCatalog); ok {
		r0 = rf(ctx, supplierID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SupplierCatalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, supplierID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierCatalogRepository_FindBySupplierAndProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierAndProduct'
type MockSupplierCatalogRepository_FindBySupplierAndProduct_Call struct {
	*mock.Call
}

// FindBySupplierAndProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID string
//   - productID string
func (_e *MockSupplierCatalogRepository_Expecter) FindBySupplierAndProduct(ctx interface{}, supplierID interface{}, productID interface{}) *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call {
	return &MockSupplierCatalogRepository_FindBySupplierAndProduct_Call{Call: _e.mock.On("FindBySupplierAndProduct", ctx, supplierID, productID)}
}

func (_c *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call) Run(run func(ctx context.Context, supplierID string, productID string)) *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call) Return(_a0 *dto.SupplierCatalog, _a1 error) *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call) RunAndReturn(run func(context.Context, string, string) (*dto.SupplierCatalog, error)) *MockSupplierCatalogRepository_FindBySupplierAndProduct_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockSupplierCatalogRepository) FindBySupplierID(ctx context.Context, supplierID string) ([]*dto.SupplierCatalogWithProduct, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 []*dto.SupplierCatalogWithProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.SupplierCatalogWithProduct, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.SupplierCatalogWithProduct); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.SupplierCatalogWithProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierCatalogRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockSupplierCatalogRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID string
func (_e *MockSupplierCatalogRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockSupplierCatalogRepository_FindBySupplierID_Call {
	return &MockSupplierCatalogRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockSupplierCatalogRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID string)) *MockSupplierCatalogRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_FindBySupplierID_Call) Return(_a0 []*dto.SupplierCatalogWithProduct, _a1 error) *MockSupplierCatalogRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierCatalogRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.SupplierCatalogWithProduct, error)) *MockSupplierCatalogRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, catalog
func (_m *MockSupplierCatalogRepository) Update(ctx context.Context, id string, catalog *dto.SupplierCatalog) error {
	ret := _m.Called(ctx, id, catalog)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.SupplierCatalog) error); ok {
		r0 = rf(ctx, id, catalog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierCatalogRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSupplierCatalogRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - catalog *dto.SupplierCatalog
func (_e *MockSupplierCatalogRepository_Expecter) Update(ctx interface{}, id interface{}, catalog interface{}) *MockSupplierCatalogRepository_Update_Call {
	return &MockSupplierCatalogRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, catalog)}
}

func (_c *MockSupplierCatalogRepository_Update_Call) Run(run func(ctx context.Context, id string, catalog *dto.SupplierCatalog)) *MockSupplierCatalogRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dto.SupplierCatalog))
	})
	return _c
}

func (_c *MockSupplierCatalogRepository_Update_Call) Return(_a0 error) *MockSupplierCatalogRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierCatalogRepository_Update_Call) RunAndReturn(run func(context.Context, string, *dto.SupplierCatalog) error) *MockSupplierCatalogRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierCatalogRepository creates a new instance of MockSupplierCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierCatalogRepository {
	mock := &MockSupplierCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
