// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncInboxRepository is an autogenerated mock type for the SyncInboxRepository type
type MockSyncInboxRepository struct {
	mock.Mock
}

type MockSyncInboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncInboxRepository) EXPECT() *MockSyncInboxRepository_Expecter {
	return &MockSyncInboxRepository_Expecter{mock: &_m.Mock}
}

// MarkApplied provides a mock function with given fields: ctx, opID
func (_m *MockSyncInboxRepository) MarkApplied(ctx context.Context, opID string) (bool, error) {
	ret := _m.Called(ctx, opID)

	if len(ret) == 0 {
		panic("no return value specified for MarkApplied")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, opID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, opID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, opID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncInboxRepository_MarkApplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkApplied'
type MockSyncInboxRepository_MarkApplied_Call struct {
	*mock.Call
}

// MarkApplied is a helper method to define mock.On call
//   - ctx context.Context
//   - opID string
func (_e *MockSyncInboxRepository_Expecter) MarkApplied(ctx interface{}, opID interface{}) *MockSyncInboxRepository_MarkApplied_Call {
	return &MockSyncInboxRepository_MarkApplied_Call{Call: _e.mock.On("MarkApplied", ctx, opID)}
}

func (_c *MockSyncInboxRepository_MarkApplied_Call) Run(run func(ctx context.Context, opID string)) *MockSyncInboxRepository_MarkApplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSyncInboxRepository_MarkApplied_Call) Return(alreadyApplied bool, err error) *MockSyncInboxRepository_MarkApplied_Call {
	_c.Call.Return(alreadyApplied, err)
	return _c
}

func (_c *MockSyncInboxRepository_MarkApplied_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSyncInboxRepository_MarkApplied_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncInboxRepository creates a new instance of MockSyncInboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncInboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncInboxRepository {
	mock := &MockSyncInboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
