// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPendingInvoiceRepository is an autogenerated mock type for the PendingInvoiceRepository type
type MockPendingInvoiceRepository struct {
	mock.Mock
}

type MockPendingInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPendingInvoiceRepository) EXPECT() *MockPendingInvoiceRepository_Expecter {
	return &MockPendingInvoiceRepository_Expecter{mock: &_m.Mock}
}

// ListDue provides a mock function with given fields: ctx, limit
func (_m *MockPendingInvoiceRepository) ListDue(ctx context.Context, limit int) ([]*dto.PendingInvoice, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDue")
	}

	var r0 []*dto.PendingInvoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*dto.PendingInvoice, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*dto.PendingInvoice); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PendingInvoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPendingInvoiceRepository_ListDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDue'
type MockPendingInvoiceRepository_ListDue_Call struct {
	*mock.Call
}

// ListDue is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockPendingInvoiceRepository_Expecter) ListDue(ctx interface{}, limit interface{}) *MockPendingInvoiceRepository_ListDue_Call {
	return &MockPendingInvoiceRepository_ListDue_Call{Call: _e.mock.On("ListDue", ctx, limit)}
}

func (_c *MockPendingInvoiceRepository_ListDue_Call) Run(run func(ctx context.Context, limit int)) *MockPendingInvoiceRepository_ListDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPendingInvoiceRepository_ListDue_Call) Return(_a0 []*dto.PendingInvoice, _a1 error) *MockPendingInvoiceRepository_ListDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPendingInvoiceRepository_ListDue_Call) RunAndReturn(run func(context.Context, int) ([]*dto.PendingInvoice, error)) *MockPendingInvoiceRepository_ListDue_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, errMsg, nextAttemptAt
func (_m *MockPendingInvoiceRepository) MarkFailed(ctx context.Context, id string, errMsg string, nextAttemptAt time.Time) error {
	ret := _m.Called(ctx, id, errMsg, nextAttemptAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, id, errMsg, nextAttemptAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPendingInvoiceRepository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockPendingInvoiceRepository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errMsg string
//   - nextAttemptAt time.Time
func (_e *MockPendingInvoiceRepository_Expecter) MarkFailed(ctx interface{}, id interface{}, errMsg interface{}, nextAttemptAt interface{}) *MockPendingInvoiceRepository_MarkFailed_Call {
	return &MockPendingInvoiceRepository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, errMsg, nextAttemptAt)}
}

func (_c *MockPendingInvoiceRepository_MarkFailed_Call) Run(run func(ctx context.Context, id string, errMsg string, nextAttemptAt time.Time)) *MockPendingInvoiceRepository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPendingInvoiceRepository_MarkFailed_Call) Return(_a0 error) *MockPendingInvoiceRepository_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingInvoiceRepository_MarkFailed_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockPendingInvoiceRepository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSubmitted provides a mock function with given fields: ctx, id
func (_m *MockPendingInvoiceRepository) MarkSubmitted(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkSubmitted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPendingInvoiceRepository_MarkSubmitted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSubmitted'
type MockPendingInvoiceRepository_MarkSubmitted_Call struct {
	*mock.Call
}

// MarkSubmitted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPendingInvoiceRepository_Expecter) MarkSubmitted(ctx interface{}, id interface{}) *MockPendingInvoiceRepository_MarkSubmitted_Call {
	return &MockPendingInvoiceRepository_MarkSubmitted_Call{Call: _e.mock.On("MarkSubmitted", ctx, id)}
}

func (_c *MockPendingInvoiceRepository_MarkSubmitted_Call) Run(run func(ctx context.Context, id string)) *MockPendingInvoiceRepository_MarkSubmitted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPendingInvoiceRepository_MarkSubmitted_Call) Return(_a0 error) *MockPendingInvoiceRepository_MarkSubmitted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingInvoiceRepository_MarkSubmitted_Call) RunAndReturn(run func(context.Context, string) error) *MockPendingInvoiceRepository_MarkSubmitted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPendingInvoiceRepository creates a new instance of MockPendingInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPendingInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPendingInvoiceRepository {
	mock := &MockPendingInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
