// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncOutboxRepository is an autogenerated mock type for the SyncOutboxRepository type
type MockSyncOutboxRepository struct {
	mock.Mock
}

type MockSyncOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncOutboxRepository) EXPECT() *MockSyncOutboxRepository_Expecter {
	return &MockSyncOutboxRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, entry
func (_m *MockSyncOutboxRepository) Append(ctx context.Context, entry *dto.SyncOutboxEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SyncOutboxEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncOutboxRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockSyncOutboxRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *dto.SyncOutboxEntry
func (_e *MockSyncOutboxRepository_Expecter) Append(ctx interface{}, entry interface{}) *MockSyncOutboxRepository_Append_Call {
	return &MockSyncOutboxRepository_Append_Call{Call: _e.mock.On("Append", ctx, entry)}
}

func (_c *MockSyncOutboxRepository_Append_Call) Run(run func(ctx context.Context, entry *dto.SyncOutboxEntry)) *MockSyncOutboxRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.SyncOutboxEntry))
	})
	return _c
}

func (_c *MockSyncOutboxRepository_Append_Call) Return(_a0 error) *MockSyncOutboxRepository_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncOutboxRepository_Append_Call) RunAndReturn(run func(context.Context, *dto.SyncOutboxEntry) error) *MockSyncOutboxRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// HasUnsyncedFromOtherOrigins provides a mock function with given fields: ctx, myOriginNodeID
func (_m *MockSyncOutboxRepository) HasUnsyncedFromOtherOrigins(ctx context.Context, myOriginNodeID string) (bool, error) {
	ret := _m.Called(ctx, myOriginNodeID)

	if len(ret) == 0 {
		panic("no return value specified for HasUnsyncedFromOtherOrigins")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, myOriginNodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, myOriginNodeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, myOriginNodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUnsyncedFromOtherOrigins'
type MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call struct {
	*mock.Call
}

// HasUnsyncedFromOtherOrigins is a helper method to define mock.On call
//   - ctx context.Context
//   - myOriginNodeID string
func (_e *MockSyncOutboxRepository_Expecter) HasUnsyncedFromOtherOrigins(ctx interface{}, myOriginNodeID interface{}) *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call {
	return &MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call{Call: _e.mock.On("HasUnsyncedFromOtherOrigins", ctx, myOriginNodeID)}
}

func (_c *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call) Run(run func(ctx context.Context, myOriginNodeID string)) *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call) Return(_a0 bool, _a1 error) *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSyncOutboxRepository_HasUnsyncedFromOtherOrigins_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnsynced provides a mock function with given fields: ctx, originNodeID, limit
func (_m *MockSyncOutboxRepository) ListUnsynced(ctx context.Context, originNodeID string, limit int) ([]*dto.SyncOutboxEntry, error) {
	ret := _m.Called(ctx, originNodeID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUnsynced")
	}

	var r0 []*dto.SyncOutboxEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*dto.SyncOutboxEntry, error)); ok {
		return rf(ctx, originNodeID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*dto.SyncOutboxEntry); ok {
		r0 = rf(ctx, originNodeID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.SyncOutboxEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, originNodeID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncOutboxRepository_ListUnsynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnsynced'
type MockSyncOutboxRepository_ListUnsynced_Call struct {
	*mock.Call
}

// ListUnsynced is a helper method to define mock.On call
//   - ctx context.Context
//   - originNodeID string
//   - limit int
func (_e *MockSyncOutboxRepository_Expecter) ListUnsynced(ctx interface{}, originNodeID interface{}, limit interface{}) *MockSyncOutboxRepository_ListUnsynced_Call {
	return &MockSyncOutboxRepository_ListUnsynced_Call{Call: _e.mock.On("ListUnsynced", ctx, originNodeID, limit)}
}

func (_c *MockSyncOutboxRepository_ListUnsynced_Call) Run(run func(ctx context.Context, originNodeID string, limit int)) *MockSyncOutboxRepository_ListUnsynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockSyncOutboxRepository_ListUnsynced_Call) Return(_a0 []*dto.SyncOutboxEntry, _a1 error) *MockSyncOutboxRepository_ListUnsynced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncOutboxRepository_ListUnsynced_Call) RunAndReturn(run func(context.Context, string, int) ([]*dto.SyncOutboxEntry, error)) *MockSyncOutboxRepository_ListUnsynced_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSynced provides a mock function with given fields: ctx, opIDs
func (_m *MockSyncOutboxRepository) MarkSynced(ctx context.Context, opIDs []string) error {
	ret := _m.Called(ctx, opIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkSynced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, opIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncOutboxRepository_MarkSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSynced'
type MockSyncOutboxRepository_MarkSynced_Call struct {
	*mock.Call
}

// MarkSynced is a helper method to define mock.On call
//   - ctx context.Context
//   - opIDs []string
func (_e *MockSyncOutboxRepository_Expecter) MarkSynced(ctx interface{}, opIDs interface{}) *MockSyncOutboxRepository_MarkSynced_Call {
	return &MockSyncOutboxRepository_MarkSynced_Call{Call: _e.mock.On("MarkSynced", ctx, opIDs)}
}

func (_c *MockSyncOutboxRepository_MarkSynced_Call) Run(run func(ctx context.Context, opIDs []string)) *MockSyncOutboxRepository_MarkSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockSyncOutboxRepository_MarkSynced_Call) Return(_a0 error) *MockSyncOutboxRepository_MarkSynced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncOutboxRepository_MarkSynced_Call) RunAndReturn(run func(context.Context, []string) error) *MockSyncOutboxRepository_MarkSynced_Call {
	_c.Call.Return(run)
	return _c
}

// PendingStats provides a mock function with given fields: ctx, originNodeID
func (_m *MockSyncOutboxRepository) PendingStats(ctx context.Context, originNodeID string) (*dto.SyncOutboxPendingStats, error) {
	ret := _m.Called(ctx, originNodeID)

	if len(ret) == 0 {
		panic("no return value specified for PendingStats")
	}

	var r0 *dto.SyncOutboxPendingStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.SyncOutboxPendingStats, error)); ok {
		return rf(ctx, originNodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.SyncOutboxPendingStats); ok {
		r0 = rf(ctx, originNodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SyncOutboxPendingStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originNodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSyncOutboxRepository_PendingStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingStats'
type MockSyncOutboxRepository_PendingStats_Call struct {
	*mock.Call
}

// PendingStats is a helper method to define mock.On call
//   - ctx context.Context
//   - originNodeID string
func (_e *MockSyncOutboxRepository_Expecter) PendingStats(ctx interface{}, originNodeID interface{}) *MockSyncOutboxRepository_PendingStats_Call {
	return &MockSyncOutboxRepository_PendingStats_Call{Call: _e.mock.On("PendingStats", ctx, originNodeID)}
}

func (_c *MockSyncOutboxRepository_PendingStats_Call) Run(run func(ctx context.Context, originNodeID string)) *MockSyncOutboxRepository_PendingStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSyncOutboxRepository_PendingStats_Call) Return(_a0 *dto.SyncOutboxPendingStats, _a1 error) *MockSyncOutboxRepository_PendingStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSyncOutboxRepository_PendingStats_Call) RunAndReturn(run func(context.Context, string) (*dto.SyncOutboxPendingStats, error)) *MockSyncOutboxRepository_PendingStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncOutboxRepository creates a new instance of MockSyncOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncOutboxRepository {
	mock := &MockSyncOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
