// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandItemSSENotifier is an autogenerated mock type for the CommandItemSSENotifier type
type MockCommandItemSSENotifier struct {
	mock.Mock
}

type MockCommandItemSSENotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandItemSSENotifier) EXPECT() *MockCommandItemSSENotifier_Expecter {
	return &MockCommandItemSSENotifier_Expecter{mock: &_m.Mock}
}

// NotifyArea provides a mock function with given fields: ctx, area, eventType, data
func (_m *MockCommandItemSSENotifier) NotifyArea(ctx context.Context, area string, eventType string, data *dto.CommandItemSSE) error {
	ret := _m.Called(ctx, area, eventType, data)

	if len(ret) == 0 {
		panic("no return value specified for NotifyArea")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dto.CommandItemSSE) error); ok {
		r0 = rf(ctx, area, eventType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandItemSSENotifier_NotifyArea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyArea'
type MockCommandItemSSENotifier_NotifyArea_Call struct {
	*mock.Call
}

// NotifyArea is a helper method to define mock.On call
//   - ctx context.Context
//   - area string
//   - eventType string
//   - data *dto.CommandItemSSE
func (_e *MockCommandItemSSENotifier_Expecter) NotifyArea(ctx interface{}, area interface{}, eventType interface{}, data interface{}) *MockCommandItemSSENotifier_NotifyArea_Call {
	return &MockCommandItemSSENotifier_NotifyArea_Call{Call: _e.mock.On("NotifyArea", ctx, area, eventType, data)}
}

func (_c *MockCommandItemSSENotifier_NotifyArea_Call) Run(run func(ctx context.Context, area string, eventType string, data *dto.CommandItemSSE)) *MockCommandItemSSENotifier_NotifyArea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dto.CommandItemSSE))
	})
	return _c
}

func (_c *MockCommandItemSSENotifier_NotifyArea_Call) Return(_a0 error) *MockCommandItemSSENotifier_NotifyArea_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandItemSSENotifier_NotifyArea_Call) RunAndReturn(run func(context.Context, string, string, *dto.CommandItemSSE) error) *MockCommandItemSSENotifier_NotifyArea_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandItemSSENotifier creates a new instance of MockCommandItemSSENotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandItemSSENotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandItemSSENotifier {
	mock := &MockCommandItemSSENotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
