// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	supplier "laguna-escondida/backend/internal/domain/aggregate/supplier"
)

// MockSupplierRepository is an autogenerated mock type for the SupplierRepository type
type MockSupplierRepository struct {
	mock.Mock
}

type MockSupplierRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierRepository) EXPECT() *MockSupplierRepository_Expecter {
	return &MockSupplierRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockSupplierRepository) Create(ctx context.Context, _a1 *supplier.Aggregate) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supplier.Aggregate) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSupplierRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *supplier.Aggregate
func (_e *MockSupplierRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockSupplierRepository_Create_Call {
	return &MockSupplierRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockSupplierRepository_Create_Call) Run(run func(ctx context.Context, _a1 *supplier.Aggregate)) *MockSupplierRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*supplier.Aggregate))
	})
	return _c
}

func (_c *MockSupplierRepository_Create_Call) Return(_a0 error) *MockSupplierRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierRepository_Create_Call) RunAndReturn(run func(context.Context, *supplier.Aggregate) error) *MockSupplierRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSupplierRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSupplierRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSupplierRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSupplierRepository_Delete_Call {
	return &MockSupplierRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSupplierRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSupplierRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierRepository_Delete_Call) Return(_a0 error) *MockSupplierRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSupplierRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockSupplierRepository) FindAll(ctx context.Context) ([]*dto.Supplier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.Supplier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.Supplier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockSupplierRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSupplierRepository_Expecter) FindAll(ctx interface{}) *MockSupplierRepository_FindAll_Call {
	return &MockSupplierRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockSupplierRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockSupplierRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSupplierRepository_FindAll_Call) Return(_a0 []*dto.Supplier, _a1 error) *MockSupplierRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.Supplier, error)) *MockSupplierRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSupplierRepository) FindByID(ctx context.Context, id string) (*dto.Supplier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Supplier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Supplier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSupplierRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSupplierRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSupplierRepository_FindByID_Call {
	return &MockSupplierRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSupplierRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockSupplierRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierRepository_FindByID_Call) Return(_a0 *dto.Supplier, _a1 error) *MockSupplierRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.Supplier, error)) *MockSupplierRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockSupplierRepository) FindByName(ctx context.Context, name string) (*dto.Supplier, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *dto.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Supplier, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Supplier); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockSupplierRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSupplierRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockSupplierRepository_FindByName_Call {
	return &MockSupplierRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockSupplierRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockSupplierRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierRepository_FindByName_Call) Return(_a0 *dto.Supplier, _a1 error) *MockSupplierRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*dto.Supplier, error)) *MockSupplierRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *MockSupplierRepository) Update(ctx context.Context, id string, _a2 *supplier.Aggregate) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *supplier.Aggregate) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSupplierRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - _a2 *supplier.Aggregate
func (_e *MockSupplierRepository_Expecter) Update(ctx interface{}, id interface{}, _a2 interface{}) *MockSupplierRepository_Update_Call {
	return &MockSupplierRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, _a2)}
}

func (_c *MockSupplierRepository_Update_Call) Run(run func(ctx context.Context, id string, _a2 *supplier.Aggregate)) *MockSupplierRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*supplier.Aggregate))
	})
	return _c
}

func (_c *MockSupplierRepository_Update_Call) Return(_a0 error) *MockSupplierRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierRepository_Update_Call) RunAndReturn(run func(context.Context, string, *supplier.Aggregate) error) *MockSupplierRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierRepository creates a new instance of MockSupplierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierRepository {
	mock := &MockSupplierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
