// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "laguna-escondida/backend/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"

	purchase_entry "laguna-escondida/backend/internal/domain/aggregate/purchase_entry"
)

// MockPurchaseEntryRepository is an autogenerated mock type for the PurchaseEntryRepository type
type MockPurchaseEntryRepository struct {
	mock.Mock
}

type MockPurchaseEntryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseEntryRepository) EXPECT() *MockPurchaseEntryRepository_Expecter {
	return &MockPurchaseEntryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entry
func (_m *MockPurchaseEntryRepository) Create(ctx context.Context, entry *purchase_entry.Aggregate) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *purchase_entry.Aggregate) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseEntryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPurchaseEntryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *purchase_entry.Aggregate
func (_e *MockPurchaseEntryRepository_Expecter) Create(ctx interface{}, entry interface{}) *MockPurchaseEntryRepository_Create_Call {
	return &MockPurchaseEntryRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *MockPurchaseEntryRepository_Create_Call) Run(run func(ctx context.Context, entry *purchase_entry.Aggregate)) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*purchase_entry.Aggregate))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_Create_Call) Return(_a0 error) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseEntryRepository_Create_Call) RunAndReturn(run func(context.Context, *purchase_entry.Aggregate) error) *MockPurchaseEntryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockPurchaseEntryRepository) FindAll(ctx context.Context) ([]*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPurchaseEntryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPurchaseEntryRepository_Expecter) FindAll(ctx interface{}) *MockPurchaseEntryRepository_FindAll_Call {
	return &MockPurchaseEntryRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) Return(_a0 []*dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPurchaseEntryRepository) FindByID(ctx context.Context, id string) (*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPurchaseEntryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPurchaseEntryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPurchaseEntryRepository_FindByID_Call {
	return &MockPurchaseEntryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) Return(_a0 *dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockPurchaseEntryRepository) FindBySupplierID(ctx context.Context, supplierID string) ([]*dto.PurchaseEntryWithSupplier, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 []*dto.PurchaseEntryWithSupplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*dto.PurchaseEntryWithSupplier, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.PurchaseEntryWithSupplier); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.PurchaseEntryWithSupplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseEntryRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockPurchaseEntryRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID string
func (_e *MockPurchaseEntryRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	return &MockPurchaseEntryRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID string)) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) Return(_a0 []*dto.PurchaseEntryWithSupplier, _a1 error) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseEntryRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, string) ([]*dto.PurchaseEntryWithSupplier, error)) *MockPurchaseEntryRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPurchaseEntryRepository creates a new instance of MockPurchaseEntryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseEntryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseEntryRepository {
	mock := &MockPurchaseEntryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
