package service

import (
	"context"
	"errors"
	"testing"
	"time"

	"laguna-escondida/backend/internal/domain/aggregate/product"
	"laguna-escondida/backend/internal/domain/dto"
	domainError "laguna-escondida/backend/internal/domain/error"
	"laguna-escondida/backend/internal/domain/ports/mocks"

	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

// Test helpers
func createTestProductService(t *testing.T) (*ProductService, *mocks.MockProductRepository) {
	mockRepo := mocks.NewMockProductRepository(t)
	return NewProductService(mockRepo), mockRepo
}

func createTestProductDTO(id, name, category string, version int, price, vat float64) *dto.Product {
	return &dto.Product{
		ID:                  id,
		Name:                name,
		Category:            category,
		Version:             version,
		TotalPriceWithTaxes: decimal.NewFromFloat(price),
		VAT:                 decimal.NewFromFloat(vat),
		SKU:                 "SKU001",
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
	}
}

// CreateProduct Tests

// Success Cases
func TestCreateProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU001",
	}

	mockRepo.On("Create", ctx, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.Name == req.Name && dto.Category == req.Category &&
			dto.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(127.0)) && dto.VAT.Equal(decimal.NewFromFloat(0.19)) &&
			dto.Version == 1 // Version should always be 1
	})).Return(nil)

	result, err := service.CreateProduct(ctx, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.NotEmpty(t, result.ID) // ID is generated by aggregate
	assert.Equal(t, req.Name, result.Name)
	assert.Equal(t, req.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should be 1
	assert.True(t, result.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(127.0)))
	assert.True(t, result.VAT.Equal(decimal.NewFromFloat(0.19)))
	assert.True(t, result.ICO.Equal(decimal.NewFromFloat(0.08)))
	assert.True(t, result.UnitPrice.Equal(decimal.NewFromFloat(100.0)))
	assert.Equal(t, req.SKU, result.SKU)

}

// Success Case - SKU with hyphen is valid
func TestCreateProduct_ValidSKU_WithHyphen(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU-001",
	}

	mockRepo.On("Create", ctx, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.SKU == "SKU-001"
	})).Return(nil)

	result, err := service.CreateProduct(ctx, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, "SKU-001", result.SKU)

}

// Error Cases

func TestCreateProduct_InvalidSKU_WithSpace(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU 001",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_INVALID_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_InvalidSKU_WithSpecialChar(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU@001",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_INVALID_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_MissingSKU(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_MISSING_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		TotalPriceWithTaxes: "100.0",
		VAT:                 "0.19",
		ICO:                 "0.08",
		TaxesFormat:         "percentage",
		Description:         nil,
		Brand:               nil,
		Model:               nil,
		SKU:                 "SKU1",
	}

	repoError := errors.New("database error")
	mockRepo.On("Create", ctx, mock.Anything).Return(repoError)

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, repoError)

}

func TestUpdateProduct_ValidSKU_WithHyphen(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 9.5)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		SKU:                 "SKU-002",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.SKU == "SKU-002"
	})).Return(nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, "SKU-002", result.SKU)

}

func TestUpdateProduct_MissingSKU(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 9.5)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		SKU:                 "",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_MISSING_SKU")

	mockRepo.AssertNotCalled(t, "Update")
}

// UpdateProduct Tests

// Success Cases
func TestUpdateProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 9.5)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		Description:         nil,
		Brand:               nil,
		Model:               nil,
		SKU:                 "SKU002",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.Name == req.Name && dto.Category == req.Category &&
			dto.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(200.0)) && dto.VAT.Equal(decimal.NewFromFloat(0.38)) &&
			dto.Version == 1 // Version should remain 1
	})).Return(nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, productID, result.ID)
	assert.Equal(t, req.Name, result.Name)
	assert.Equal(t, req.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should remain 1
	assert.True(t, result.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(200.0)))
	assert.True(t, result.VAT.Equal(decimal.NewFromFloat(0.38)))
	assert.True(t, result.ICO.Equal(decimal.NewFromFloat(0.12)))
	assert.True(t, result.UnitPrice.Equal(decimal.NewFromFloat(133.33)))
	assert.Equal(t, req.SKU, result.SKU)

}

// Error Cases
func TestUpdateProduct_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "0.38",
		ICO:                 "0.16",
		TaxesFormat:         "percentage",
		SKU:                 "SKU003",
	}

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

	mockRepo.AssertNotCalled(t, "Update")
}

func TestUpdateProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 9.5)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "0.38",
		ICO:                 "0.16",
		TaxesFormat:         "percentage",
		SKU:                 "SKU004",
	}

	updateFailedError := errors.New("update failed")
	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.Anything).Return(updateFailedError)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, updateFailedError)

}

// DeleteProduct Tests

// Success Cases
func TestDeleteProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 19.0)

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Delete", ctx, productID).Return(nil)

	err := service.DeleteProduct(ctx, productID)

	require.NoError(t, err)
}

// Error Cases
func TestDeleteProduct_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	err := service.DeleteProduct(ctx, productID)

	require.Error(t, err)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

	mockRepo.AssertNotCalled(t, "Delete")
}

func TestDeleteProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 19.0)

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Delete", ctx, productID).Return(errors.New("delete failed"))

	err := service.DeleteProduct(ctx, productID)

	require.Error(t, err)
	assert.ErrorIs(t, err, domainError.ErrProductDeleteFailed)

}

// ListProducts Tests

// Success Cases
func TestListProducts_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	products := []*dto.Product{
		createTestProductDTO("product-1", "Product 1", "Category A", 1, 100.0, 19.0),
		createTestProductDTO("product-2", "Product 2", "Category B", 1, 200.0, 38.0),
	}

	mockRepo.On("FindAll", ctx).Return(products, nil)

	result, err := service.ListProducts(ctx)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Len(t, result, 2)
	assert.Equal(t, products[0].ID, result[0].ID)
	assert.Equal(t, products[1].ID, result[1].ID)

}

func TestListProducts_EmptyList(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	mockRepo.On("FindAll", ctx).Return([]*dto.Product{}, nil)

	result, err := service.ListProducts(ctx)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Empty(t, result)

}

// Error Cases
func TestListProducts_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	mockRepo.On("FindAll", ctx).Return(nil, errors.New("database error"))

	result, err := service.ListProducts(ctx)

	require.Error(t, err)
	assert.Nil(t, result)

}

// GetProductByID Tests

// Success Cases
func TestGetProductByID_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	expectedProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 19.0)

	mockRepo.On("FindByID", ctx, productID).Return(expectedProduct, nil)

	result, err := service.GetProductByID(ctx, productID)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, expectedProduct.ID, result.ID)
	assert.Equal(t, expectedProduct.Name, result.Name)
	assert.Equal(t, expectedProduct.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should be 1

}

// Error Cases
func TestGetProductByID_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	result, err := service.GetProductByID(ctx, productID)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

}
