package service

import (
	"context"
	"errors"
	"testing"
	"time"

	"laguna-escondida/backend/internal/domain/aggregate/product"
	"laguna-escondida/backend/internal/domain/dto"
	domainError "laguna-escondida/backend/internal/domain/error"
	"laguna-escondida/backend/internal/domain/ports/mocks"

	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

// Test helpers
func createTestProductService(t *testing.T) (*ProductService, *mocks.MockProductRepository) {
	mockRepo := mocks.NewMockProductRepository(t)
	mockSupplierRepo := mocks.NewMockSupplierRepository(t)
	mockCatalogRepo := mocks.NewMockSupplierCatalogRepository(t)
	return NewProductService(mockRepo, mockSupplierRepo, mockCatalogRepo), mockRepo
}

func createTestProductServiceWithAllMocks(t *testing.T) (*ProductService, *mocks.MockProductRepository, *mocks.MockSupplierRepository, *mocks.MockSupplierCatalogRepository) {
	mockRepo := mocks.NewMockProductRepository(t)
	mockSupplierRepo := mocks.NewMockSupplierRepository(t)
	mockCatalogRepo := mocks.NewMockSupplierCatalogRepository(t)
	return NewProductService(mockRepo, mockSupplierRepo, mockCatalogRepo), mockRepo, mockSupplierRepo, mockCatalogRepo
}

func createTestProductDTO(id, name, category string, version int, totalPrice, vatPercentage, icoPercentage float64) *dto.Product {
	total := decimal.NewFromFloat(totalPrice)
	vatPct := decimal.NewFromFloat(vatPercentage)
	icoPct := decimal.NewFromFloat(icoPercentage)

	// Calculate tax amounts using the same formula as the aggregate
	divisor := decimal.NewFromInt(1).Add(vatPct).Add(icoPct)
	vatAmount := total.Mul(vatPct).Div(divisor).Round(2)
	icoAmount := total.Mul(icoPct).Div(divisor).Round(2)
	unitPrice := total.Sub(vatAmount).Sub(icoAmount)

	return &dto.Product{
		ID:                  id,
		Name:                name,
		Category:            category,
		ProductType:         dto.ProductTypeSellable,
		UnitOfMeasure:       dto.UnitOfMeasureUnit,
		Version:             version,
		UnitPrice:           unitPrice,
		TotalPriceWithTaxes: total,
		VAT:                 vatPct,
		VATAmount:           vatAmount,
		ICO:                 icoPct,
		ICOAmount:           icoAmount,
		SKU:                 "SKU001",
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
	}
}

// CreateProduct Tests

// Success Cases
func TestCreateProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU001",
	}

	mockRepo.On("Create", ctx, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.Name == req.Name && dto.Category == req.Category &&
			dto.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(127.0)) && dto.VAT.Equal(decimal.NewFromFloat(0.19)) &&
			dto.Version == 1 // Version should always be 1
	})).Return(nil)

	result, err := service.CreateProduct(ctx, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.NotEmpty(t, result.ID) // ID is generated by aggregate
	assert.Equal(t, req.Name, result.Name)
	assert.Equal(t, req.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should be 1
	assert.True(t, result.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(127.0)))
	assert.True(t, result.VAT.Equal(decimal.NewFromFloat(0.19)))
	assert.True(t, result.ICO.Equal(decimal.NewFromFloat(0.08)))
	assert.Equal(t, req.SKU, result.SKU)

	// Verify the invariant: unitPrice + vatAmount + icoAmount == totalPriceWithTaxes
	calculatedTotal := result.UnitPrice.Add(result.VATAmount).Add(result.ICOAmount)
	assert.True(t, calculatedTotal.Equal(result.TotalPriceWithTaxes),
		"Invariant violated: unitPrice(%s) + vatAmount(%s) + icoAmount(%s) = %s, expected %s",
		result.UnitPrice, result.VATAmount, result.ICOAmount, calculatedTotal, result.TotalPriceWithTaxes)

}

// Success Case - SKU with hyphen is valid
func TestCreateProduct_ValidSKU_WithHyphen(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU-001",
	}

	mockRepo.On("Create", ctx, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.SKU == "SKU-001"
	})).Return(nil)

	result, err := service.CreateProduct(ctx, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, "SKU-001", result.SKU)

}

// Error Cases

func TestCreateProduct_InvalidSKU_WithSpace(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU 001",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_INVALID_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_InvalidSKU_WithSpecialChar(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "SKU@001",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_INVALID_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_MissingSKU(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "127.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		SKU:                 "",
	}

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_MISSING_SKU")

	mockRepo.AssertNotCalled(t, "Create")
}

func TestCreateProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	req := &dto.CreateProductRequest{
		Name:                "Test Product",
		Category:            "Category A",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "100.0",
		VAT:                 "19",
		ICO:                 "8",
		TaxesFormat:         "percentage",
		Description:         nil,
		SKU:                 "SKU1",
	}

	repoError := errors.New("database error")
	mockRepo.On("Create", ctx, mock.Anything).Return(repoError)

	result, err := service.CreateProduct(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, repoError)

}

func TestUpdateProduct_ValidSKU_WithHyphen(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 0.095, 0.05)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		SKU:                 "SKU-002",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.SKU == "SKU-002"
	})).Return(nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, "SKU-002", result.SKU)

}

func TestUpdateProduct_MissingSKU(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 0.095, 0.05)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		SKU:                 "",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.Contains(t, err.Error(), "PRODUCT_MISSING_SKU")

	mockRepo.AssertNotCalled(t, "Update")
}

// UpdateProduct Tests

// Success Cases
func TestUpdateProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 0.095, 0.05)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38.0",
		ICO:                 "12.0",
		TaxesFormat:         "percentage",
		Description:         nil,
		SKU:                 "SKU002",
	}

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.MatchedBy(func(p *product.Aggregate) bool {
		dto := p.ToDTO()
		return dto.Name == req.Name && dto.Category == req.Category &&
			dto.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(200.0)) && dto.VAT.Equal(decimal.NewFromFloat(0.38)) &&
			dto.Version == 1 // Version should remain 1
	})).Return(nil)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, productID, result.ID)
	assert.Equal(t, req.Name, result.Name)
	assert.Equal(t, req.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should remain 1
	assert.True(t, result.TotalPriceWithTaxes.Equal(decimal.NewFromFloat(200.0)))
	assert.True(t, result.VAT.Equal(decimal.NewFromFloat(0.38)))
	assert.True(t, result.ICO.Equal(decimal.NewFromFloat(0.12)))
	assert.Equal(t, req.SKU, result.SKU)

	// Verify the invariant: unitPrice + vatAmount + icoAmount == totalPriceWithTaxes
	calculatedTotal := result.UnitPrice.Add(result.VATAmount).Add(result.ICOAmount)
	assert.True(t, calculatedTotal.Equal(result.TotalPriceWithTaxes),
		"Invariant violated: unitPrice(%s) + vatAmount(%s) + icoAmount(%s) = %s, expected %s",
		result.UnitPrice, result.VATAmount, result.ICOAmount, calculatedTotal, result.TotalPriceWithTaxes)

}

// Error Cases
func TestUpdateProduct_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38",
		ICO:                 "16",
		TaxesFormat:         "percentage",
		SKU:                 "SKU003",
	}

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

	mockRepo.AssertNotCalled(t, "Update")
}

func TestUpdateProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Old Name", "Old Category", 1, 50.0, 0.095, 0.05)

	req := &dto.UpdateProductRequest{
		Name:                "New Name",
		Category:            "New Category",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		TotalPriceWithTaxes: "200.0",
		VAT:                 "38",
		ICO:                 "16",
		TaxesFormat:         "percentage",
		SKU:                 "SKU004",
	}

	updateFailedError := errors.New("update failed")
	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Update", ctx, productID, mock.Anything).Return(updateFailedError)

	result, err := service.UpdateProduct(ctx, productID, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, updateFailedError)

}

// DeleteProduct Tests

// Success Cases
func TestDeleteProduct_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 0.19, 0.08)

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Delete", ctx, productID).Return(nil)

	err := service.DeleteProduct(ctx, productID)

	require.NoError(t, err)
}

// Error Cases
func TestDeleteProduct_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	err := service.DeleteProduct(ctx, productID)

	require.Error(t, err)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

	mockRepo.AssertNotCalled(t, "Delete")
}

func TestDeleteProduct_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	existingProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 0.19, 0.08)

	mockRepo.On("FindByID", ctx, productID).Return(existingProduct, nil)
	mockRepo.On("Delete", ctx, productID).Return(errors.New("delete failed"))

	err := service.DeleteProduct(ctx, productID)

	require.Error(t, err)
	assert.ErrorIs(t, err, domainError.ErrProductDeleteFailed)

}

// ListProducts Tests

// Success Cases
func TestListProducts_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	products := []*dto.Product{
		createTestProductDTO("product-1", "Product 1", "Category A", 1, 100.0, 0.19, 0.08),
		createTestProductDTO("product-2", "Product 2", "Category B", 1, 200.0, 0.38, 0.12),
	}

	mockRepo.On("FindAll", ctx).Return(products, nil)

	result, err := service.ListProducts(ctx)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Len(t, result, 2)
	assert.Equal(t, products[0].ID, result[0].ID)
	assert.Equal(t, products[1].ID, result[1].ID)

}

func TestListProducts_EmptyList(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	mockRepo.On("FindAll", ctx).Return([]*dto.Product{}, nil)

	result, err := service.ListProducts(ctx)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Empty(t, result)

}

// Error Cases
func TestListProducts_RepositoryError(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	mockRepo.On("FindAll", ctx).Return(nil, errors.New("database error"))

	result, err := service.ListProducts(ctx)

	require.Error(t, err)
	assert.Nil(t, result)

}

// GetProductByID Tests

// Success Cases
func TestGetProductByID_Success(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"
	expectedProduct := createTestProductDTO(productID, "Product", "Category", 1, 100.0, 0.19, 0.08)

	mockRepo.On("FindByID", ctx, productID).Return(expectedProduct, nil)

	result, err := service.GetProductByID(ctx, productID)

	require.NoError(t, err)
	assert.NotNil(t, result)
	assert.Equal(t, expectedProduct.ID, result.ID)
	assert.Equal(t, expectedProduct.Name, result.Name)
	assert.Equal(t, expectedProduct.Category, result.Category)
	assert.Equal(t, 1, result.Version) // Version should be 1

}

// Error Cases
func TestGetProductByID_ProductNotFound(t *testing.T) {
	ctx := context.Background()
	service, mockRepo := createTestProductService(t)

	productID := "product-1"

	mockRepo.On("FindByID", ctx, productID).Return(nil, errors.New("not found"))

	result, err := service.GetProductByID(ctx, productID)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrProductNotFound)

}

// BulkCreateProducts Tests

func createBulkItem(name, sku, vat, ico, totalPrice string) dto.BulkCreateProductItem {
	return dto.BulkCreateProductItem{
		Name:                name,
		Category:            "SNACKS",
		ProductType:         "SELLABLE",
		UnitOfMeasure:       "unit",
		VAT:                 vat,
		ICO:                 ico,
		TaxesFormat:         "percentage",
		SKU:                 sku,
		TotalPriceWithTaxes: totalPrice,
	}
}

// Success Cases
func TestBulkCreateProducts_AllNew(t *testing.T) {
	ctx := context.Background()
	svc, mockRepo, _, _ := createTestProductServiceWithAllMocks(t)

	req := &dto.BulkCreateProductRequest{
		Items: []dto.BulkCreateProductItem{
			createBulkItem("Product A", "SKU-A", "19", "8", "6500"),
			createBulkItem("Product B", "SKU-B", "19", "8", "3200"),
			createBulkItem("Product C", "SKU-C", "5", "8", "1500"),
		},
	}

	mockRepo.On("FindBySKUs", ctx, []string{"SKU-A", "SKU-B", "SKU-C"}).Return([]*dto.Product{}, nil)
	mockRepo.On("Create", ctx, mock.Anything).Return(nil).Times(3)

	result, err := svc.BulkCreateProducts(ctx, req)

	require.NoError(t, err)
	assert.Len(t, result.Created, 3)
	assert.Empty(t, result.Errors)
}

func TestBulkCreateProducts_WithSupplierLinking(t *testing.T) {
	ctx := context.Background()
	svc, mockRepo, mockSupplierRepo, mockCatalogRepo := createTestProductServiceWithAllMocks(t)

	supplierID := "supplier-123"
	supplierSKU := "S001"
	req := &dto.BulkCreateProductRequest{
		SupplierID: &supplierID,
		Items: []dto.BulkCreateProductItem{
			{
				Name:                "Product A",
				Category:            "SNACKS",
				ProductType:         "SELLABLE",
				UnitOfMeasure:       "unit",
				VAT:                 "19",
				ICO:                 "8",
				TaxesFormat:         "percentage",
				SKU:                 "SKU-A",
				TotalPriceWithTaxes: "6500",
				SupplierSKU:         &supplierSKU,
			},
		},
	}

	mockSupplierRepo.On("FindByID", ctx, supplierID).Return(&dto.Supplier{ID: supplierID, Name: "Ramo"}, nil)
	mockRepo.On("FindBySKUs", ctx, []string{"SKU-A"}).Return([]*dto.Product{}, nil)
	mockRepo.On("Create", ctx, mock.Anything).Return(nil)
	mockCatalogRepo.On("Create", ctx, mock.MatchedBy(func(c *dto.SupplierCatalog) bool {
		return c.SupplierID == supplierID && c.SupplierSKU != nil && *c.SupplierSKU == "S001"
	})).Return(nil)

	result, err := svc.BulkCreateProducts(ctx, req)

	require.NoError(t, err)
	assert.Len(t, result.Created, 1)
	assert.Empty(t, result.Errors)
	mockCatalogRepo.AssertCalled(t, "Create", ctx, mock.Anything)
}

// Partial Success Cases
func TestBulkCreateProducts_PartialWithDuplicates(t *testing.T) {
	ctx := context.Background()
	svc, mockRepo, _, _ := createTestProductServiceWithAllMocks(t)

	req := &dto.BulkCreateProductRequest{
		Items: []dto.BulkCreateProductItem{
			createBulkItem("New Product", "SKU-NEW", "19", "8", "6500"),
			createBulkItem("Existing Product", "SKU-EXISTING", "19", "8", "3200"),
		},
	}

	existingProduct := createTestProductDTO("p-1", "Existing Product", "SNACKS", 1, 3200, 0.19, 0.08)
	existingProduct.SKU = "SKU-EXISTING"

	mockRepo.On("FindBySKUs", ctx, []string{"SKU-NEW", "SKU-EXISTING"}).Return([]*dto.Product{existingProduct}, nil)
	mockRepo.On("Create", ctx, mock.Anything).Return(nil)

	result, err := svc.BulkCreateProducts(ctx, req)

	require.NoError(t, err)
	assert.Len(t, result.Created, 1)
	assert.Len(t, result.Errors, 1)
	assert.Equal(t, 1, result.Errors[0].Index)
	assert.Equal(t, "SKU-EXISTING", result.Errors[0].SKU)
	assert.Contains(t, result.Errors[0].Message, "already exists")
}

func TestBulkCreateProducts_AllDuplicates(t *testing.T) {
	ctx := context.Background()
	svc, mockRepo, _, _ := createTestProductServiceWithAllMocks(t)

	req := &dto.BulkCreateProductRequest{
		Items: []dto.BulkCreateProductItem{
			createBulkItem("Product A", "SKU-A", "19", "8", "6500"),
			createBulkItem("Product B", "SKU-B", "19", "8", "3200"),
		},
	}

	existingA := createTestProductDTO("p-1", "Product A", "SNACKS", 1, 6500, 0.19, 0.08)
	existingA.SKU = "SKU-A"
	existingB := createTestProductDTO("p-2", "Product B", "SNACKS", 1, 3200, 0.19, 0.08)
	existingB.SKU = "SKU-B"

	mockRepo.On("FindBySKUs", ctx, []string{"SKU-A", "SKU-B"}).Return([]*dto.Product{existingA, existingB}, nil)

	result, err := svc.BulkCreateProducts(ctx, req)

	require.NoError(t, err)
	assert.Empty(t, result.Created)
	assert.Len(t, result.Errors, 2)
	mockRepo.AssertNotCalled(t, "Create")
}

// Error Cases
func TestBulkCreateProducts_InvalidSupplierID(t *testing.T) {
	ctx := context.Background()
	svc, _, mockSupplierRepo, _ := createTestProductServiceWithAllMocks(t)

	supplierID := "invalid-supplier"
	req := &dto.BulkCreateProductRequest{
		SupplierID: &supplierID,
		Items: []dto.BulkCreateProductItem{
			createBulkItem("Product A", "SKU-A", "19", "8", "6500"),
		},
	}

	mockSupplierRepo.On("FindByID", ctx, supplierID).Return(nil, errors.New("not found"))

	result, err := svc.BulkCreateProducts(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrSupplierNotFound)
}

func TestBulkCreateProducts_EmptyItems(t *testing.T) {
	ctx := context.Background()
	svc, _, _, _ := createTestProductServiceWithAllMocks(t)

	req := &dto.BulkCreateProductRequest{
		Items: []dto.BulkCreateProductItem{},
	}

	result, err := svc.BulkCreateProducts(ctx, req)

	require.Error(t, err)
	assert.Nil(t, result)
	assert.ErrorIs(t, err, domainError.ErrProductCreationFailed)
}

func TestBulkCreateProducts_ValidationFailure(t *testing.T) {
	ctx := context.Background()
	svc, mockRepo, _, _ := createTestProductServiceWithAllMocks(t)

	req := &dto.BulkCreateProductRequest{
		Items: []dto.BulkCreateProductItem{
			createBulkItem("Good Product", "SKU-GOOD", "19", "8", "6500"),
			{
				Name:                "Bad Product",
				Category:            "SNACKS",
				ProductType:         "SELLABLE",
				UnitOfMeasure:       "unit",
				VAT:                 "invalid",
				ICO:                 "8",
				TaxesFormat:         "percentage",
				SKU:                 "SKU-BAD",
				TotalPriceWithTaxes: "3200",
			},
		},
	}

	mockRepo.On("FindBySKUs", ctx, []string{"SKU-GOOD", "SKU-BAD"}).Return([]*dto.Product{}, nil)
	mockRepo.On("Create", ctx, mock.Anything).Return(nil)

	result, err := svc.BulkCreateProducts(ctx, req)

	require.NoError(t, err)
	assert.Len(t, result.Created, 1)
	assert.Len(t, result.Errors, 1)
	assert.Equal(t, 1, result.Errors[0].Index)
	assert.Equal(t, "SKU-BAD", result.Errors[0].SKU)
}
